### PR TITLE
fix: block-1339346-context-revert-twice

### LINKED ISSUE #1117: 1339346 - context revert twice
## Ranges

```rust
1339346-1339346
```

## Issue

Error fetching or parsing JSON: 'result' {'jsonrpc': '2.0', 'id': 1, 'error': {'code': -32603, 'message': 'Plugin internal error', 'data': 'Exceptions triggered while tracing:\n  - a context can not self-revert twice\n  - a context can not self-revert twice\n'}}
Failed to fetch or parse JSON data for blockNumber=1339346: 'result'

### PR DESCRIPTION
**Pull request by letypequividelespoubelles**
… the right moment

### CODE REVIEW

File: arithmetization/src/main/java/net/consensys/linea/zktracer/opcode/gas/projector/DataCopy.java [hunk 1]
```diff
@@ -15,29 +15,26 @@
...
 public final class DataCopy extends GasProjection {
   private final MessageFrame frame;
-  private long offset = 0;
+  private long destOffset = 0;
   private long len = 0;
 
   public DataCopy(MessageFrame frame, OpCode opCode) {
     this.frame = frame;
     if (frame.stackSize() > 2) {
-      if (opCode == OpCode.CODECOPY) {
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/opcode/gas/projector/DataCopy.java:35]: THis was the issue, using the wrong offset to compute memoryExpansion

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java [hunk 2]
```diff
@@ -657,13 +658,9 @@ public void traceContextExit(MessageFrame frame) {
     // TODO: why only do this at positive depth ?
     if (frame.getDepth() > 0) {
 
-      DeploymentExceptions contextExceptions =
+      final DeploymentExceptions contextExceptions =
           DeploymentExceptions.fromFrame(this.currentFrame(), frame);
       this.currentTraceSection().setContextExceptions(contextExceptions);
-
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java:663]: it was indeed a duplicate, it's now done only at TracePreopcode

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java [hunk 3]
```diff
@@ -1006,6 +999,10 @@ void processStateExec(MessageFrame frame) {
 
       new StackOnlySection(this);
     }
+
+    if (Exceptions.any(pch().exceptions()) || opCode() == REVERT) {
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java:1003]: we were setting the revert stamp BEFORE creating the section, and as we increase the hubStamp when creating the section, we gave h-1 for the revert stamp, not h.

File: linea-constraints
Comment (letypequividelespoubelles) [inline linea-constraints:1]: just updated to the latest master

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java (hunk 3 above)
Comment (OlivierBBB) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java:1003]: Nice

File: arithmetization/src/main/java/net/consensys/linea/zktracer/opcode/gas/projector/DataCopy.java [hunk 4]
```diff
@@ -15,29 +15,26 @@
...
-        this.offset = clampedToLong(frame.getStackItem(0));
-      } else {
-        this.offset = clampedToLong(frame.getStackItem(1));
-      }
-      this.len = clampedToLong(frame.getStackItem(2));
+      destOffset = clampedToLong(frame.getStackItem(0));
+      len = clampedToLong(frame.getStackItem(2));
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/opcode/gas/projector/DataCopy.java:37]: Could we use `source`/`target` to remain consistent with everything else ? Also `size` rather than `len` ?

Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/opcode/gas/projector/DataCopy.java]: Could we use `source`/`target` to remain consistent with everything else ? Also `size` rather than `len` ?

Comment (OlivierBBB) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/opcode/gas/projector/DataCopy.java]: Also: is this consistent with the distinction `EXTCODECOPY` / `CODECOPY` ? Or is `EXTCODECOPY` dealt with elsewhere ?

File: arithmetization/src/main/java/net/consensys/linea/zktracer/runtime/callstack/CallFrame.java [hunk 5]
```diff
@@ -318,23 +318,22 @@ private void revertChildren(CallStack callStack, int parentRevertStamp) {
...
   }
 
-  public void revert(CallStack callStack, int revertStamp) {
+  public void setRevertStamps(CallStack callStack, int currentStamp) {
     if (selfReverts) {
-      throw new IllegalStateException("a context can not self-revert twice");
+      throw new IllegalStateException(
+          String.format(
+              "a context can not self-revert twice, it already reverts at %s, can't revert again at %s",
+              revertStamp, currentStamp));
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/runtime/callstack/CallFrame.java:326]: 👍

**Review by OlivierBBB — APPROVED** [review]

File: arithmetization/src/main/java/net/consensys/linea/zktracer/opcode/gas/projector/DataCopy.java (hunk 4 above)
Comment (letypequividelespoubelles) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/opcode/gas/projector/DataCopy.java]: ExtCodeCopy is dealt elsewhere
