### PR TITLE
fix(modexp): add debuged failing ref test

### LINKED ISSUE #1497: modexp_d20g0v0_London size has value 0.
Multiple reference tests wials with error "size has value 0." which comes from checks in MmioData where size is expected to be positive.

### PR DESCRIPTION
**Pull request by letypequividelespoubelles**

### CODE REVIEW

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/precompiles/ModexpMetadata.java [hunk 1]
```diff
@@ -122,7 +122,7 @@ public EWord rawLeadingWord() {
   }
 
   public boolean extractModulus() {
-    return (callData.size() > MBS_MIN_OFFSET + bbsInt() + ebsInt()) && !mbs().isZero();
+    return (callData.size() > BASE_MIN_OFFSET + bbsInt() + ebsInt()) && !mbs().isZero();
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/precompiles/ModexpMetadata.java:125]: The only fix :)

Comment (OlivierBBB) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/precompiles/ModexpMetadata.java:125]: LGTM 🙂

**Review by OlivierBBB — APPROVED** [review]
