### PR TITLE
No longer convert `SHF_STAMP` to short

### LINKED ISSUE #1407: SHF stamp issue
- @gusiri 's failing ranges: https://drive.google.com/drive/folders/1_UivK6UgGhBOQrmRSkmLr25MYdqD2KcK?usp=drive_link
- issue: the `SHIFT_STAMP` becomes negative once it hits `0x8000`

image

### PR DESCRIPTION
**Pull request by OlivierBBB**

### CODE REVIEW

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/shf/ShfOperation.java [hunk 1]
```diff
@@ -198,9 +198,9 @@ public void trace(Trace trace, int stamp) {
           .shb6Lo(shb.getShbLo()[6 - 3][i])
           .shb7Hi(shb.getShbHi()[7 - 3][i])
           .shb7Lo(shb.getShbLo()[7 - 3][i])
-          .shiftDirection(this.isShiftRight)
+          .shiftDirection(isShiftRight)
           .iomf(true)
-          .shiftStamp((short) stamp)
+          .shiftStamp(stamp)
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/shf/ShfOperation.java:203]: The only relevant change.

**Review by letypequividelespoubelles — APPROVED** [review]
