### PR TITLE
fix: BlockCapturer for Created Accounts

### LINKED ISSUE #1289: Fix BlockCapturer Handling of Contract Creation
The `BlockCapturer` is not always handling contract creation correctly.  I believe this is the sequence where it fails:

- Constract is created
- Contract state is modified in some way

Then, the block capturer adds the account being created to the initial set of `accounts` in the conflation, along with storage values for the locations assigned (where each location is assigned `0x0` because it didn't exist before the conflation).  This then results in BESU thinking the contract already exists at creation time, leading to a failure.

### PR DESCRIPTION
**Pull request by DavePearce**
The block capturer had an issue capturing accounts which were created during the execution of the conflation being captured.  The problematic scenario required an account to exist at the beginning of the conflation, but which was then the subject of a CREATE/CREATE2 contract creation.  This is permitted in certain situations, such as when the account only has a balance (but no storage).

To resolve this case, we have to be a little more careful when creating storage snapshots.  Specifically, when an account only partially exists (i.e. has no storage, but only a balance) then we never create storage snapshots.

Finally, this also adds a debugging mode to ReplayExecutionEnvironment to assist debugging the BlockCapturer.

### CODE REVIEW

File: arithmetization/src/main/java/net/consensys/linea/blockcapture/snapshots/StorageSnapshot.java [hunk 1]
```diff
@@ -19,17 +19,36 @@
...
-    return Optional.ofNullable(world.get(address))
-        .map(
-            account ->
-                new StorageSnapshot(
-                    address.toHexString(),
-                    key.toHexString(),
-                    account.getStorageValue(key).toHexString()));
+    // Lookup account that was touched
+    Account account = world.get(address);
+    // Check account *really* exists from a storage perspective.  This is important to distinguish
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/blockcapture/snapshots/StorageSnapshot.java:30]: So in the EYP lingo account existence is equivalent to satisfying at least one of the three conditions below:
- nonzero balance
- nonzero nonce
- nonempty code

Storage is notably absent from that definition.

Comment (DavePearce) [reply arithmetization/src/main/java/net/consensys/linea/blockcapture/snapshots/StorageSnapshot.java:30]: So, the code used in BESU is:

```java
  private static boolean accountExists(final Account account) {
    // The account exists if it has sent a transaction
    // or already has its code initialized.
    return account.getNonce() != 0 || !account.getCode().isEmpty() || !account.isStorageEmpty();
  }
```

If this returns `true` then account creation fails.

File: arithmetization/src/main/java/net/consensys/linea/blockcapture/snapshots/StorageSnapshot.java [hunk 2]
```diff
@@ -19,17 +19,36 @@
...
+    // for accounts which are created *during* the conflation.  Such accounts may have technically
+    // existed before the conflation (e.g. they had a non-zero balance) but could still have been
+    // "created" during the conflation.  In such case, this snapshot would be simply assigning 0x0
+    // to the given storage locations.  However, we don't want to create a storage snapshot in such
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/blockcapture/snapshots/StorageSnapshot.java:34]: Does taking a storage snapshot insert a storage value ?

Comment (OlivierBBB) [reply arithmetization/src/main/java/net/consensys/linea/blockcapture/snapshots/StorageSnapshot.java:34]: Also, at least according to the current EYP, storage does not matter when it comes to checking the possibility of doing a CREATE2

image

Comment (DavePearce) [reply arithmetization/src/main/java/net/consensys/linea/blockcapture/snapshots/StorageSnapshot.java:34]: > Also, at least according to the current EYP

Yeah, but at the end of the day, we are not measuring against the EYP.  We are comparing against execution on MAINNET using BESU.  What I'm looking at is what BESU does.  If that deviates from the EYP ... well, we still have to follow BESU.

However, I agree that it does seem wierd and I can follow up with BESU to see why they do it that way (or even it could be a bug).

Comment (DavePearce) [reply arithmetization/src/main/java/net/consensys/linea/blockcapture/snapshots/StorageSnapshot.java:34]: > Does taking a storage snapshot insert a storage value ?

Yes, in the replay environment it does.  See `ReplayExecutionEnvironment.initWorld()`.  One option might be to drop `StorageSnapshots` which assign `0x0` at the beginning of the conflation.  It has the same effect.  Maybe you prefer this?

Comment (OlivierBBB) [reply arithmetization/src/main/java/net/consensys/linea/blockcapture/snapshots/StorageSnapshot.java:34]: But does taking a storage snapshot change the world state ? If so that is a massive problem.

Comment (OlivierBBB) [reply arithmetization/src/main/java/net/consensys/linea/blockcapture/snapshots/StorageSnapshot.java:34]: In any case we do want to define storage snapshots even if the target account has empty storage or doesn't even exist yet. Simply because it's possible in Ethereum and we will want to test that, see https://github.com/Consensys/linea-tracer/issues/1205, but it should be side-effect free

File: arithmetization/src/main/java/net/consensys/linea/blockcapture/snapshots/StorageSnapshot.java [hunk 3]
```diff
@@ -19,17 +19,36 @@
...
+          new StorageSnapshot(
+              address.toHexString(),
+              key.toHexString(),
+              account.getStorageValue(key).toHexString()));
+    } else {
+      return Optional.empty();
+    }
+  }
+
+  private static boolean accountExists(final Account account) {
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/blockcapture/snapshots/StorageSnapshot.java:48]: AFAIU the EYP defines for an account $a$
- `existence` as existence in the state, i.e. $\sigma[a] \neq \varnothing$
- `EMPTY` as having nontrivial nonce, balance or code
- `DEAD` as either not existing or being empty
- prohibited from being deployed at as existing and either having nontrivial nonce, code or storage


image

image

along with [EIP-7610](https://eips.ethereum.org/EIPS/eip-7610)

So maybe a more accurate name would be `accountMayNotBeDeployedAt` / `deploymentIsProhibitedAt` or so.

**Review by OlivierBBB — APPROVED** [review]
LGTM though there were parts where I'm not sure what's going on (e.g. the `executeFrom`)
