### PR TITLE
fix: really same list of module for all fork

### LINKED ISSUE #2312: still diff between london modules and cancun modules

### PR DESCRIPTION
**Pull request by letypequividelespoubelles**

### CODE REVIEW

File: arithmetization/src/test/java/net/consensys/linea/LineCountingTracerTest.java [hunk 1]
```diff
@@ -46,4 +48,73 @@ void noDuplicateNamesInModules() {
...
+          cancunTracer.contains(module), "Module " + module + " is in London but not in Cancun");
+    }
+
+    // check that shanghai ⊆ london
+    for (String module : pragueTracer) {
+      checkArgument(
+          londonTracer.contains(module), "Module " + module + " is in Prague but not in London");
+    }
+
+    // check that london ⊆ paris
```
Comment (amkCha) [inline arithmetization/src/test/java/net/consensys/linea/LineCountingTracerTest.java]: london and prague here

File: arithmetization/src/test/java/net/consensys/linea/LineCountingTracerTest.java [hunk 2]
```diff
@@ -46,4 +48,73 @@ void noDuplicateNamesInModules() {
...
+    }
+
+    // check that london ⊆ cancun
+    for (String module : londonTracer) {
+      checkArgument(
+          cancunTracer.contains(module), "Module " + module + " is in London but not in Cancun");
+    }
+
+    // check that shanghai ⊆ london
+    for (String module : pragueTracer) {
```
Comment (amkCha) [inline arithmetization/src/test/java/net/consensys/linea/LineCountingTracerTest.java:109]: shanghai & london or prague & london ?

File: arithmetization/src/test/java/net/consensys/linea/LineCountingTracerTest.java [hunk 3]
```diff
@@ -46,4 +48,73 @@ void noDuplicateNamesInModules() {
...
+
+    // check that london ⊆ Shanghai
+    for (String module : londonTracer) {
+      checkArgument(
+          shanghaiTracer.contains(module),
+          "Module " + module + " is in London but not in Shanghai");
+    }
+
+    // check that shanghai ⊆ london
+    for (String module : cancunTracer) {
```
Comment (amkCha) [inline arithmetization/src/test/java/net/consensys/linea/LineCountingTracerTest.java:97]: to be sure we test all cases, should it be the comment of the message one ?

Comment (letypequividelespoubelles) [reply arithmetization/src/test/java/net/consensys/linea/LineCountingTracerTest.java:97]: wdym ?

**Review by amkCha — APPROVED** [review]

File: arithmetization/src/test/java/net/consensys/linea/LineCountingTracerTest.java (hunk 3 above)
Comment (amkCha) [reply arithmetization/src/test/java/net/consensys/linea/LineCountingTracerTest.java:97]: it was the comment, all good now !
