### PR TITLE
fix(mmio): use `TBO` for `ramToLimb` instructions

### LINKED ISSUE #1189: fix ramToLimbSingleSource doesn't read TBO

### PR DESCRIPTION
**Pull request by letypequividelespoubelles**

### CODE REVIEW

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmio/MmioData.java [hunk 1]
```diff
@@ -214,13 +214,16 @@ public void onePartialToTwo(
   }
 
   public void oneToOnePadded(
-      final Bytes16 sourceBytes, final short sourceOffsetTrigger, final short size) {
+      final Bytes16 sourceBytes,
+      final short sourceOffsetTrigger,
+      final short targetByteOffsetTrigger,
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmio/MmioData.java]: What's the reason for the `Trigger` terminology ?

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmio/MmioData.java [hunk 2]
```diff
@@ -214,13 +214,16 @@ public void onePartialToTwo(
...
+      final short size) {
 
     for (short ct = 0; ct < LLARGE; ct++) {
 
       bit1.add(ct, plateau(sourceOffsetTrigger, ct));
       bit2.add(ct, plateau(sourceOffsetTrigger + size, ct));
-      bit3.add(ct, plateau(size, ct));
+      bit3.add(ct, plateau(targetByteOffsetTrigger + size, ct));
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmio/MmioData.java]: In the spec we write some preconditions that we should add here.

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmio/MmioPatterns.java [hunk 3]
```diff
@@ -154,24 +154,6 @@ public static Bytes16 onePartialToTwoOutputTwo(
...
-      final short sourceByteOffset,
-      final short size) {
-    final short numberOfBytesFromFirstSource = (short) (LLARGE - sourceByteOffset);
-
-    return Bytes16.leftPad(
-        Bytes.concatenate(
-            source1.slice(sourceByteOffset, numberOfBytesFromFirstSource),
-            source2.slice(0, size - numberOfBytesFromFirstSource)));
-  }
-
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmio/MmioPatterns.java:174]: Were these methods redundant ?

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmio/MmioData.java (hunk 2 above)
Comment (OlivierBBB) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmio/MmioData.java]: For `[1 => 1 Padded]`
image

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmio/MmioData.java [hunk 4]
```diff
@@ -241,13 +244,14 @@ public void twoToOnePadded(
...
+      final short targetOffsetTrigger,
       final short size) {
 
     for (short ct = 0; ct < LLARGE; ct++) {
       bit1.add(ct, plateau(sourceOffsetTrigger, ct));
       bit2.add(ct, plateau(sourceOffsetTrigger + size - LLARGE, ct));
-      bit3.add(ct, plateau(LLARGE - sourceOffsetTrigger, ct));
-      bit4.add(ct, plateau(size, ct));
+      bit3.add(ct, plateau(targetOffsetTrigger + LLARGE - sourceOffsetTrigger, ct));
+      bit4.add(ct, plateau(targetOffsetTrigger + size, ct));
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmio/MmioData.java]: Similarly here for `[2 => 1 Padded]`
image

**Review by OlivierBBB — CHANGES_REQUESTED** [review]
The `checkArguments` may catch mistakes.

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmio/MmioData.java (hunk 1 above)
Comment (letypequividelespoubelles) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmio/MmioData.java]: no reason, just historic from the go implem I guess. The name in the spec is BlaMarker which is not ideal neither

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmio/MmioData.java (hunk 2 above)
Comment (letypequividelespoubelles) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmio/MmioData.java]: checkArgument added

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmio/MmioPatterns.java (hunk 3 above)
Comment (letypequividelespoubelles) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmio/MmioPatterns.java:174]: no, just unused and wrong method

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmio/MmioData.java (hunk 4 above)
Comment (letypequividelespoubelles) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmio/MmioData.java]: checkArgument added

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmio/MmioData.java (hunk 1 above)
Comment (OlivierBBB) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmio/MmioData.java]: I may just change these to become byte offsets in the spec rather than markers.

**Review by OlivierBBB — APPROVED** [review]
LGTM
