### PR TITLE
`SELFDESTRUCT` fix for Cancun

### LINKED ISSUE #2237: cancun reference tests debuging - selfdestruct
failing constraint: failing constraint hub.selfdestruct-instruction---setting-balance-and-marked-for-SELFDESTRUCT-for-first-account-row#2:

one of the many failing tests for similar reason:

blockchainreferencetest_98, callcodecall_10_SuicideEnd

### PR DESCRIPTION
**Pull request by OlivierBBB**
- fixes `SELFDESTRUCT` for Cancun
- implements more lenient upper limits for `NUMBER` and `TIMESTAMP` in `BLOCK_DATA`

### CODE REVIEW

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/blockdata/moduleOperation/BlockdataOperation.java [hunk 1]
```diff
@@ -59,7 +59,7 @@ public abstract class BlockdataOperation extends ModuleOperation {
   private final BlockHeader blockHeader;
   private final BlockHeader prevBlockHeader;
   private static final EWord POWER_256_20 = EWord.of(TWOFIFTYSIX_TO_THE_TWENTY);
-  private static final EWord POWER_256_6 = EWord.of(BigInteger.ONE.shiftLeft(6 * 8));
+  private static final EWord POWER_256_8 = EWord.of(BigInteger.ONE.shiftLeft(8 * 8));
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/blockdata/moduleOperation/BlockdataOperation.java:62]: could use the same const as in the lisp as we do with `private static final EWord POWER_256_20 = EWord.of(TWOFIFTYSIX_TO_THE_TWENTY);`

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/systemTransaction/EIP4788BeaconBlockRootSection.java [hunk 2]
```diff
@@ -74,7 +77,9 @@ public EIP4788BeaconBlockRootSection(
     fragments().add(accountFragment);
 
     if (isNonTrivialOperation) {
-      final EWord keyTimestamp = EWord.of(timestamp % HISTORY_BUFFER_LENGTH);
+      final BigInteger timestampMod8191 =
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/systemTransaction/EIP4788BeaconBlockRootSection.java:80]: the modulo8191 is a short, not a BigInt

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/systemTransaction/EIP4788BeaconBlockRootSection.java [hunk 3]
```diff
@@ -50,7 +53,7 @@ public EIP4788BeaconBlockRootSection(
     super(hub, (short) 5);
     final AccountSnapshot beaconrootAccount =
         AccountSnapshot.canonical(hub, world, EIP4788_BEACONROOT_ADDRESS, false);
-    final long timestamp = blockHeader.getTimestamp();
+    final BigInteger timestamp = longToUnsignedBigInteger(blockHeader.getTimestamp());
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/systemTransaction/EIP4788BeaconBlockRootSection.java:56]: ok for now, but we'll have to change this when I'm done with the Besu PR: https://github.com/Consensys/linea-tracer/issues/2241

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/txndata/rows/hubRows/HubRow.java [hunk 4]
```diff
@@ -37,8 +37,9 @@ public void traceRow(Trace.Txndata trace) {
     trace
         .hub(true)
         .pHubBtcBlockNumber(header.getNumber())
-        .pHubBtcBlockGasLimit(header.getGasLimit())
-        .pHubBtcBasefee(header.getBaseFee().get().getAsBigInteger().longValueExact())
+        .pHubBtcBlockGasLimit(Bytes.ofUnsignedLong(header.getGasLimit()))
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/txndata/rows/hubRows/HubRow.java:40]: what happens if gasLimit is `0xFFFFFFFFFFFFFFFF` ?

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/txndata/rows/hubRows/HubRow.java [hunk 5]
```diff
@@ -37,8 +37,9 @@ public void traceRow(Trace.Txndata trace) {
...
+        .pHubBtcBasefee(
+            Bytes.ofUnsignedLong(header.getBaseFee().get().getAsBigInteger().longValueExact()))
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/txndata/rows/hubRows/HubRow.java:42]: betterUse bigIntToBytes, less conversion

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/txndata/rows/hubRows/HubRowForUserTransactions.java [hunk 6]
```diff
@@ -44,9 +44,9 @@ public void traceRow(Trace.Txndata trace) {
         .pHubIsDeployment(txn.isDeployment())
         .pHubNonce(Bytes.ofUnsignedLong(txn.getBesuTransaction().getNonce()))
         .pHubValue(bigIntegerToBytes(txn.getBesuTransaction().getValue().getAsBigInteger()))
-        .pHubGasLimit(txn.getBesuTransaction().getGasLimit())
+        .pHubGasLimit(Bytes.ofUnsignedLong(txn.getBesuTransaction().getGasLimit()))
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/txndata/rows/hubRows/HubRowForUserTransactions.java:47]: why having a :i128 in the constraints if in any case it's stored as a long in besu ? Same remark for all other typing change.

**Review by letypequividelespoubelles — COMMENTED** [review]
LGTM for the selfdestruct, some concerns about the type change, I don't see why we have :i128 if besu stores info as long

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/systemTransaction/EIP4788BeaconBlockRootSection.java (hunk 2 above)
Comment (OlivierBBB) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/systemTransaction/EIP4788BeaconBlockRootSection.java:80]: I did this because there were tests with very large TIMESTAMP which got interpreted as a negative number. And even the remainder was interpreted that way ...

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/txndata/rows/hubRows/HubRow.java (hunk 4 above)
Comment (OlivierBBB) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/txndata/rows/hubRows/HubRow.java:40]: I imagine it works as intended, no ? since it gets it as an unsigned integer rather than -1 as java would.

**Comment by OlivierBBB** [comment]
Merging early and addressing comments in future PR, see
- https://github.com/Consensys/linea-tracer/issues/2261
- https://github.com/Consensys/linea-constraints/issues/751
