### PR TITLE
Fix for NPE in `SelfdestructSection`

### LINKED ISSUE #1216: NPE in a `deepCopy` of an `AccountSnapshot` related to a `SELFDESTRUCT`
## Blocks

```rust
// Network: Sepolia
2392659
```

## Issue

```
time  curl -X POST 'http://localhost:15480' --data '{"jsonrpc":"2.0","method":"linea_getBlockTracesCountersV2","params": [{ "blockNumber": 2392659, "expectedTracesEngineVersion": "v0.6.0-rc1" }],    "id": 1
 }'
{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"Plugin internal error","data":"Exceptions triggered while tracing:\n  - Cannot invoke \"net.consensys.linea.zktracer.module.hub.AccountSnapshot.deepCopy()\" because \"this.selfdestructorAccountAfter\" is null\n"}}
```

### PR DESCRIPTION
**Pull request by OlivierBBB**

### CODE REVIEW

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/halt/SelfdestructSection.java [hunk 1]
```diff
@@ -115,23 +110,28 @@ public SelfdestructSection(Hub hub) {
     if (Exceptions.any(exceptions)) {
       checkArgument(exceptions == OUT_OF_GAS_EXCEPTION);
 
-      selfDestroyerFirstAccountFragment =
+      recipientAccountBefore =
+          selfdestructTargetsItself
+              ? selfdestructorAccountBefore
+              : AccountSnapshot.canonical(hub, recipientAddress);
+
+      selfdestructorFirstAccountFragment =
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/halt/SelfdestructSection.java:118]: In case of an OOGX there is only `Before` data. We adjst the snapshots accordingly.

File: arithmetization/src/test/java/net/consensys/linea/zktracer/Issue1216Tests.java [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+
+import org.junit.jupiter.api.Tag;
+import org.junit.jupiter.api.Test;
+
+public class Issue1216Tests {
+
+  @Tag("nightly")
+  @Tag("replay")
+  @Test
+  void issue_1216_sepolia_block_2392659() {
```
Comment (letypequividelespoubelles) [inline arithmetization/src/test/java/net/consensys/linea/zktracer/Issue1216Tests.java:47]: could you add comment on what was failing ?

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/halt/SelfdestructSection.java [hunk 3]
```diff
@@ -84,15 +84,10 @@ public SelfdestructSection(Hub hub) {
     selfdestructorAccountBefore = AccountSnapshot.canonical(hub, addressWhichMaySelfDestruct);
 
     // Recipient
-    recipientRawAddress = frame.getStackItem(0);
-    recipientAddress = Address.extract(Bytes32.leftPad(recipientRawAddress));
+    recipientAddressUntrimmed = frame.getStackItem(0);
+    recipientAddress = Address.extract(Bytes32.leftPad(recipientAddressUntrimmed));
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/halt/SelfdestructSection.java:88]: stupid question, don't we need to trigger TRM ? Id on't see it triggered in the section

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/AccountSnapshot.java [hunk 4]
```diff
@@ -177,6 +177,17 @@ public AccountSnapshot incrementBalanceBy(Wei quantity) {
     return this;
   }
 
+  /**
+   * {@link AccountSnapshot#setBalanceToZero()} changes the balance of the AccountSnapshot to be
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/AccountSnapshot.java:181]: CAn we have the same comment as others "Be
   * sure to work with a {@link AccountSnapshot#deepCopy} if necessary." bla bla ?

**Review by letypequividelespoubelles — APPROVED** [review]
LGTM

File: arithmetization/src/test/java/net/consensys/linea/zktracer/Issue1216Tests.java (hunk 2 above)
Comment (OlivierBBB) [reply arithmetization/src/test/java/net/consensys/linea/zktracer/Issue1216Tests.java:47]: Yep

Comment (OlivierBBB) [reply arithmetization/src/test/java/net/consensys/linea/zktracer/Issue1216Tests.java:47]: Done.

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/halt/SelfdestructSection.java (hunk 3 above)
Comment (OlivierBBB) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/halt/SelfdestructSection.java:88]: No, you are right. We trigger it in the OOGX case (`makeWithTrm`) but not in the unexceptional case (`make`). It's fixed now. Good catch.

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/AccountSnapshot.java (hunk 4 above)
Comment (OlivierBBB) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/AccountSnapshot.java:181]: Yes, will add

Comment (OlivierBBB) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/AccountSnapshot.java:181]: Donc

**Comment by OlivierBBB** [comment]
This PR subsumes https://github.com/Consensys/linea-tracer/pull/1113 and further incorporates the three (previously) failing ranges from https://github.com/Consensys/linea-tracer/issues/1104
