### PR TITLE
fix(Identity): tgt offset for partial return data copy

### LINKED ISSUE #1528: EcMul memory consistency fails
ref test 532

### PR DESCRIPTION
**Pull request by letypequividelespoubelles**

### CODE REVIEW

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/imc/mmu/MmuCall.java [hunk 1]
```diff
@@ -440,7 +441,7 @@ public static MmuCall forIdentityReturnData(
         .targetId(hub.currentFrame().contextNumber())
         .targetRamBytes(Optional.of(precompileSubsection.callerMemorySnapshot))
         .sourceOffset(EWord.ZERO)
-        .targetOffset(EWord.of(precompileSubsection.parentReturnDataTarget.offset()))
+        .referenceOffset(precompileSubsection.parentReturnDataTarget.offset())
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/imc/mmu/MmuCall.java:444]: The only fix, the rest is using constant instead of values

Comment (OlivierBBB) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/imc/mmu/MmuCall.java:444]: I guess the `targetOffset` at 0 is implicit ? Do we want to add it like for the `sourceOffset` ?

**Review by OlivierBBB — APPROVED** [review]
LGTM

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/imc/mmu/MmuCall.java (hunk 1 above)
Comment (letypequividelespoubelles) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/imc/mmu/MmuCall.java:444]: It's not in the hub->MMU interface so it's unspecified, so IMHO it's better to leave it as it is
