### PR TITLE
IDENTITY size parameter fix

### LINKED ISSUE #1560: Identity SIZE parameter fix

### PR DESCRIPTION
**Pull request by OlivierBBB**

### CODE REVIEW

**Review by letypequividelespoubelles — APPROVED** [review]
LGTM

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/imc/mmu/MmuCall.java [hunk 1]
```diff
@@ -429,17 +430,20 @@ public static MmuCall forIdentityExtractCallData(final Hub hub, PrecompileSubsec
...
+    checkState(subsection.callDataSize() == subsection.returnDataSize());
+    checkState(subsection.returnDataOffset() == 0);
+
     return new MmuCall(hub, MMU_INST_RAM_TO_RAM_SANS_PADDING)
         .sourceId(subsection.exoModuleOperationId())
         .sourceRamBytes(Optional.of(subsection.returnDataRange.extract()))
         .targetId(hub.currentFrame().contextNumber())
         .targetRamBytes(Optional.of(subsection.rawCallerMemory()))
         .sourceOffset(EWord.ZERO)
+        .size(subsection.returnDataSize())
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/imc/mmu/MmuCall.java:445]: This is the real fix.
