### PR TITLE
fix(return): OOGX for return for deployment + call SHAKIRA for return…

### LINKED ISSUE #1103: block 1002387 - return issue

### PR DESCRIPTION
**Pull request by letypequividelespoubelles**
… + cleaning

### CODE REVIEW

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/imc/mmu/opcode/ReturnFromDeployment.java [hunk 1]
```diff
@@ -39,10 +41,14 @@ public ReturnFromDeployment(final Hub hub) {
...
-    // TODO: get the metaData directly from the hub
     final Address contractAddress = hub.messageFrame().getContractAddress();
     final int depNumber = hub.deploymentNumberOf(contractAddress);
-    this.contract = ContractMetadata.underDeployment(contractAddress, depNumber);
+    contract = ContractMetadata.underDeployment(contractAddress, depNumber);
+
+    final ShakiraDataOperation shakiraDataOperation =
+      new ShakiraDataOperation(hub.stamp(), KECCAK, hub.romLex().getCodeByMetadata(contract));
+
+    hub.shakiraData().call(shakiraDataOperation);
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/imc/mmu/opcode/ReturnFromDeployment.java:51]: OK

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/halt/ReturnSection.java [hunk 2]
```diff
@@ -146,6 +145,12 @@ public ReturnSection(Hub hub) {
       return;
     }
 
+    // OOGX case
+    if (Exceptions.outOfGasException(exceptions) && returnFromDeployment) {
+      checkArgument(exceptions == OUT_OF_GAS_EXCEPTION);
+      return;
+    }
+
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/halt/ReturnSection.java:154]: Ok

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/shakiradata/ShakiraDataOperation.java [hunk 3]
```diff
@@ -41,39 +42,41 @@
...
-    this.hashType = precompileType;
-    this.ID = hubStamp + 1;
-    this.hashInput = hashInput;
-    this.inputSize = hashInput.size();
-    this.lastNBytes = (short) (inputSize % LLARGE == 0 ? LLARGE : inputSize % LLARGE);
+    final long hubStamp, final HashFunction hashFunction, final Bytes input) {
+    final Bytes32 hash = keccak256(input);
+
+    hashType = hashFunction;
+    ID = hubStamp + 1;
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/shakiradata/ShakiraDataOperation.java]: We have a function for that, something like `ExoModuleId(int h)` or so.

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/shakiradata/ShakiraDataOperation.java [hunk 4]
```diff
@@ -41,39 +42,41 @@
...
-    this.hashType = precompileType;
-    this.ID = hubStamp + 1;
-    this.hashInput = hashInput;
-    this.inputSize = hashInput.size();
-    this.lastNBytes = (short) (inputSize % LLARGE == 0 ? LLARGE : inputSize % LLARGE);
+      final HashFunction hashFunction,
+      final Bytes input,
+      final Bytes hash) {
+    hashType = hashFunction;
+    ID = hubStamp + 1;
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/shakiradata/ShakiraDataOperation.java]: Same

**Review by OlivierBBB — CHANGES_REQUESTED** [review]

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/shakiradata/ShakiraDataOperation.java (hunk 3 above)
Comment (OlivierBBB) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/shakiradata/ShakiraDataOperation.java]: Done

**Review by OlivierBBB — APPROVED** [review]
