### PR TITLE
fix: many things ...

### LINKED ISSUE #1004: range 6020023 ,6020029
## Ranges

```rust
6020023-6020029
```

## Issue

time curl --location --request POST 'localhost:15480' --header 'Content-Type: application/json' --data-raw '{"jsonrpc": "2.0", "method": "linea_generateConflatedTracesToFileV2", "params":[{"startBlockNumber": 6020023 , "endBlockNumber":6020029 , "expectedTracesEngineVersion": "0.5.0-beta"}], "id": 1}'
{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"Plugin internal error","data":"Exceptions triggered while tracing:\n  - Cannot invoke \"java.util.Set.add(Object)\" because \"this.destructedAccountsSnapshot\" is null\n  - null\n  - Cannot invoke \"java.util.Set.add(Object)\" because \"this.destructedAccountsSnapshot\" is null\n  - null\n  - Cannot invoke \"java.util.Set.add(Object)\" because \"this.destructedAccountsSnapshot\" is null\n  - Index -1 out of bounds for length 0\n  - null\n  - Cannot invoke \"java.util.Set.add(Object)\" because \"this.destructedAccountsSnapshot\" is null\n  - Index -1 out of bounds for length 0\n"}}
error:

@Override
public void resolvePostTransaction(
    Hub hub, WorldView state, Transaction tx, boolean isSuccessful) {
  if (selfDestructWasReverted) {
    return;
  }

  Map<EphemeralAccount, Integer> effectiveSelfDestructMap =
      this.transactionProcessingMetadata.getEffectiveSelfDestructMap();
  EphemeralAccount ephemeralAccount =
      new EphemeralAccount(this.address, this.accountAfter.deploymentNumber());
  Preconditions.checkArgument(effectiveSelfDestructMap.containsKey(ephemeralAccount));
effectiveSelfDestructMap is empty which indicates that  TransactionProcessingMetadata.resolvePostTransaction is not called before.

### LINKED ISSUE #1006: range 6032696  6032699
## Ranges

```rust
6032696-6032699
```

## Issue

time curl --location --request POST 'localhost:15480' --header 'Content-Type: application/json' --data-raw '{"jsonrpc": "2.0", "method": "linea_generateConflatedTracesToFileV2", "params":[{"startBlockNumber": 6032696 , "endBlockNumber":6032699 , "expectedTracesEngineVersion": "0.5.0-beta"}], "id": 1}'
{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"Plugin internal error","data":"Exceptions triggered while tracing:\n  - null\n"}}

Preconditions.checkArgument(
    hub.currentFrame().isDeployment() == deploymentStatus); // sanity check
deploymentStatus
deploymentStatus is true  but  hub.currentFrame().isDeployment() is false
this is in StopSection()

### LINKED ISSUE #1014: Fix: MXP / ROMLEX problem with "deployment number 0"
_(to recreate this requires the fix for #998 to have been applied --- hopefully this will be merged shortly)_

There is some kind of problem affecting the `fatMxp()` and `testMxpRandomAdvanced()` tests which only appears after the fix for #998.  I have marked these tests as `@Disabled` temporarily until this issue is resolved.  The trace is:

```
Exceptions triggered while tracing:
  - RomChunk with address 0x6ff1019c622e4641f86f4bb7232b7901b8d20db6, deployment number 0 and deploymentStatus true not found


java.lang.RuntimeException: RomChunk with address 0x6ff1019c622e4641f86f4bb7232b7901b8d20db6, deployment number 0 and deploymentStatus true not found
	at net.consensys.linea.zktracer.module.romlex.RomLex.getCodeFragmentIndexByMetadata(RomLex.java:99)
	at net.consensys.linea.zktracer.module.hub.fragment.account.AccountFragment.resolvePostConflation(AccountFragment.java:197)
	at net.consensys.linea.zktracer.module.hub.defer.DeferRegistry.resolvePostConflation(DeferRegistry.java:142)
	at net.consensys.linea.zktracer.module.hub.Hub.traceEndConflation(Hub.java:467)
```

@letypequividelespoubelles @lorenzogentile404 FYI

### PR DESCRIPTION
**Pull request by OlivierBBB**
WIP

### CODE REVIEW

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java [hunk 1]
```diff
@@ -655,11 +658,11 @@ public void traceContextReEnter(MessageFrame frame) {
   @Override
   public void traceContextExit(MessageFrame frame) {
     this.currentFrame().initializeFrame(frame); // TODO: is it needed ?
+
+    exitDeploymentFromDeploymentInfoPointOfView();
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java:662]: method extraction + the update is done only when necessary

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java [hunk 2]
```diff
@@ -655,11 +658,11 @@ public void traceContextReEnter(MessageFrame frame) {
...
+
+    // TODO: why only do this at positive depth ?
     if (frame.getDepth() > 0) {
-      this.transients
-          .conflation()
-          .deploymentInfo()
-          .unmarkDeploying(this.currentFrame().byteCodeAddress());
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java:662]: This needed to happen at every depth + only when necessary

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java [hunk 3]
```diff
@@ -669,6 +672,8 @@ public void traceContextExit(MessageFrame frame) {
         this.callStack.revert(this.state.stamps().hub()); // TODO: Duplicate s?
       }
 
+      defers.resolveUponExitingContext(this, currentFrame());
+
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java]: We were somehow missing this ?!

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java [hunk 4]
```diff
@@ -705,6 +710,25 @@ public void traceContextExit(MessageFrame frame) {
...
+            == (messageFrame().getType() == MessageFrame.Type.CONTRACT_CREATION));
+
+    if (currentDeploymentStatus()) {
+      transients
+          .conflation()
+          .deploymentInfo()
+          .markAsNotUnderDeployment(this.currentFrame().byteCodeAddress());
+    }
+  }
+
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java:725]: Extraction of method + sanity check

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java [hunk 5]
```diff
@@ -1072,4 +1097,20 @@ public void squashParentFrameReturnData() {
...
+  public final int deploymentNumberOf(Address address) {
+    return transients.conflation().deploymentInfo().deploymentNumber(address);
+  }
+
+  public final boolean currentDeploymentStatus() {
+    return deploymentStatusOf(this.messageFrame().getContractAddress());
+  }
+
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java:1112]: Quality of life

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java [hunk 6]
```diff
@@ -1072,4 +1097,20 @@ public void squashParentFrameReturnData() {
...
+  public final boolean deploymentStatusOf(Address address) {
+    return transients.conflation().deploymentInfo().getDeploymentStatus(address);
+  }
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java:1101]: Quality of life

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxInitializationSection.java [hunk 7]
```diff
@@ -48,53 +49,69 @@ public TxInitializationSection(Hub hub, WorldView world) {
...
-              tx.isReceiverPreWarmed(),
-              deploymentInfo.number(toAddress),
-              deploymentInfo.isDeploying(toAddress));
+              recipientAddress,
+              tx.isRecipientPreWarmed(),
+              deploymentInfo.deploymentNumber(recipientAddress),
+              deploymentInfo.getDeploymentStatus(recipientAddress));
+    }
+
+    if (isDeployment) {
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxInitializationSection.java:90]: doing the deployment from the `DeploymentInfo` pov

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxInitializationSection.java [hunk 8]
```diff
@@ -48,53 +49,69 @@ public TxInitializationSection(Hub hub, WorldView world) {
...
+      deploymentInfo.newDeploymentAt(recipientAddress);
     }
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxInitializationSection.java:92]: doing the deployment from the DeploymentInfo pov

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/romlex/RomLex.java [hunk 9]
```diff
@@ -301,4 +327,21 @@ public void commit(List<MappedByteBuffer> buffers) {
...
+        ContractMetadata.make(
+            hub.messageFrame().getContractAddress(),
+            hub.currentDeploymentNumber(),
+            hub.currentDeploymentStatus());
+
+    checkArgument(!hub.currentDeploymentStatus());
+
+    final RomChunk chunk = new RomChunk(contractMetadata, false, true, byteCode);
+    this.chunks.add(chunk);
+  }
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/romlex/RomLex.java:332]: The deployment info has been updated when appropriate in `traceContextExit`.

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/romlex/RomLex.java [hunk 10]
```diff
@@ -210,29 +210,29 @@ public void callRomLex(final MessageFrame frame) {
...
 
-        Optional.ofNullable(frame.getWorldUpdater().get(calledAddress))
+        final int foreignDeploymentNumber = hub.deploymentNumberOf(foreignCodeAddress);
+        final boolean foreignDeploymentStatus = hub.deploymentStatusOf(foreignCodeAddress);
+
+        checkArgument(length > 0, "EXTCODECOPY should only trigger a ROM_LEX chunk if nonzero size parameter");
+        checkArgument(!foreignDeploymentStatus, "EXTCODECOPY should only trigger a ROM_LEX chunk if its target isn't currently deploying");
+        checkArgument(!frame.getWorldUpdater().getAccount(foreignCodeAddress).isEmpty() && frame.getWorldUpdater().getAccount(foreignCodeAddress).hasCode());
+
+        Optional.ofNullable(frame.getWorldUpdater().get(foreignCodeAddress))
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/romlex/RomLex.java:227]: EXTCODECOPY foreign address fix: `frame.getContractAddress()` returns the address of the currently executing bytecode. For the `RomChunk` we are building for `EXTCODECOPY` we only care about the `foreignAddress`.

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/romlex/RomLex.java [hunk 11]
```diff
@@ -241,15 +241,22 @@ public void callRomLex(final MessageFrame frame) {
...
+        ContractMetadata.underDeployment(address, deploymentNumber);
+
+    checkArgument(deploymentStatus, "After a CREATE the deployment status should be true");
 
-    final RomChunk chunk = new RomChunk(contractMetadata, true, false, this.byteCode);
-    this.chunks.add(chunk);
-    this.createDefers.trigger(contractMetadata);
+    final RomChunk chunk = new RomChunk(contractMetadata, true, false, byteCode);
+    chunks.add(chunk);
+    createDefers.trigger(contractMetadata);
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/romlex/RomLex.java:264]: CREATE's are deferred to `ContextEntry`

I kept 
```java
createDefers.trigger(contractMetadata);
```
as I didn't look into what it does.

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/romlex/RomLex.java [hunk 12]
```diff
@@ -46,7 +51,8 @@
 import org.hyperledger.besu.evm.worldstate.WorldView;
 
 @Accessors(fluent = true)
-public class RomLex implements Module, PostOpcodeDefer {
+public class RomLex
+    implements Module, PostOpcodeDefer, ImmediateContextEntryDefer, ContextExitDefer {
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/romlex/RomLex.java:54]: `ImmediateContextEntryDefer` for CREATE(2)
`ContextExitDefer` for RETURN

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/transients/DeploymentInfo.java [hunk 13]
```diff
@@ -32,28 +36,45 @@ public class DeploymentInfo {
...
+    this.markAsUnderDeployment(address);
   }
 
-  public void deploy(Address address) {
-    this.deploymentNumber.put(address, this.number(address) + 1);
-    this.markDeploying(address);
+  public void newDeploymentAtForTxSkip(Address address) {
+    this.incrementDeploymentNumber(address);
+    this.markAsNotUnderDeployment(address);
+  }
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/transients/DeploymentInfo.java:51]: `newDeploymentAtForTxSkip` is special as one immediately transitions to a deployed account with empty code.

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/halt/SelfdestructSection.java [hunk 14]
```diff
@@ -69,27 +70,27 @@ public SelfdestructSection(Hub hub) {
...
+    hubStamp = hub.stamp();
+    exceptions = hub.pch().exceptions();
 
     final MessageFrame frame = hub.messageFrame();
 
     // Account
-    this.address = frame.getSenderAddress();
-    this.accountBefore = AccountSnapshot.canonical(hub, this.address);
+    address = frame.getRecipientAddress();
+    selfdestructorAccountBefore = AccountSnapshot.canonical(hub, address);
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/halt/SelfdestructSection.java:82]: Fixed major mix up where the address to  SELFDESTRUCT was declared to be the caller (or creator) rather than the callee (or createe) 😅

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/halt/SelfdestructSection.java [hunk 15]
```diff
@@ -69,27 +70,27 @@ public SelfdestructSection(Hub hub) {
...
-    this.selfDestructTargetsItself = this.address.equals(this.recipientAddress);
+    selfDestructTargetsItself = address.equals(recipientAddress);
 
-    this.recipientAccountBefore =
+    recipientAccountBefore =
         selfDestructTargetsItself
-            ? this.accountAfter.deepCopy()
-            : AccountSnapshot.canonical(hub, this.recipientAddress);
+            ? selfdestructorAccountAfter.deepCopy()
+            : AccountSnapshot.canonical(hub, recipientAddress);
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/halt/SelfdestructSection.java:93]: **Question:** will this work for the deployment number and status ? We must have tests with SELFDESTRUCT's during CREATE(2)'s or during deployment transactions.

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java (hunk 3 above)
Comment (letypequividelespoubelles) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java]: no, it's already done at the end of `traceContextExit` 
image

Comment (letypequividelespoubelles) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java]: we need to do it for any depth, I delete your add.

Comment (letypequividelespoubelles) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java]: https://github.com/Consensys/linea-tracer/pull/1027/commits/b859713fabb537eefc15cb75e16ade62fa630f0b

Comment (OlivierBBB) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java]: Indeed

**Comment by OlivierBBB** [comment]
Connected to both

https://github.com/Consensys/linea-tracer/issues/1004
https://github.com/Consensys/linea-tracer/issues/1006

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/romlex/RomLex.java [hunk 16]
```diff
@@ -103,7 +104,7 @@ public int getCodeFragmentIndexByMetadata(final ContractMetadata metadata) {
     throw new RuntimeException(
         String.format(
             "RomChunk with address %s, deployment number %s and deploymentStatus %s not found",
-            metadata.address(), metadata.deploymentNumber(), !metadata.underDeployment()));
+            metadata.address(), metadata.deploymentNumber(), metadata.underDeployment()));
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/romlex/RomLex.java:106]: This was printing the wrong information in the error message.

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/romlex/RomLex.java [hunk 17]
```diff
@@ -188,9 +189,8 @@ public void callRomLex(final MessageFrame frame) {
 
       case CALL, CALLCODE, DELEGATECALL, STATICCALL -> {
         final Address calledAddress = Words.toAddress(frame.getStackItem(1));
-        final Address contractAddress = frame.getContractAddress();
-        final int depNumber = hub.deploymentNumberOf(contractAddress);
-        final boolean depStatus = hub.deploymentStatusOf(contractAddress);
+        final int depNumber = hub.deploymentNumberOf(calledAddress);
+        final boolean depStatus = hub.deploymentStatusOf(calledAddress);
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/romlex/RomLex.java:192]: The `frame.contractAddress` is the address of the bytecode executing in the current execution context (or frame.) What we need is the deployment information of the code we are trying to `EXTCODECOPY` from

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/copy/ExtCodeCopySection.java [hunk 18]
```diff
@@ -122,8 +122,10 @@ public ExtCodeCopySection(Hub hub) {
             .accountFragment()
             .makeWithTrm(accountBefore, accountAfter, rawAddress, doingDomSubStamps);
     accountDoingFragment.requiresRomlex(triggerCfi);
+    if (triggerCfi) {
+      hub.romLex().callRomLex(hub.messageFrame());
+    }
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/copy/ExtCodeCopySection.java:127]: We should trigger the ROM and ROM_LEX modules iff it is deemed necessary (`trigger_ROMLEX = true` or in the old notation `triggerCfi = true`)

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/halt/StopSection.java [hunk 19]
```diff
@@ -50,7 +50,7 @@ public StopSection(Hub hub) {
     hub.defers().scheduleForPostTransaction(this); // always
 
     hubStamp = hub.stamp();
-    address = hub.currentFrame().accountAddress();
+    address = hub.messageFrame().getContractAddress();
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/halt/StopSection.java:53]: We care about the address of the code that's currently running, not about the address of the account that's running it.

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/storage/StorageFragment.java [hunk 20]
```diff
@@ -43,20 +43,35 @@ public final class StorageFragment implements TraceFragment {
...
+
+    List<State.StorageSlotIdentifier> sameAddressAsCurrentSsi = current.keySet()
+            .stream()
+            .filter(key -> key.getAddress().equals(storageSlotIdentifier.getAddress()))
+            .toList();
+
+    int x = 42;
+
+    checkArgument(match);
+    checkArgument(containsActualStorageSlotIdentifier);
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/storage/StorageFragment.java:65]: TODO: remove, this was for testing purposes

Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/storage/StorageFragment.java:58]: TODO: remove, this was for testing purposes

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/storage/StorageFragmentPurpose.java [hunk 21]
```diff
@@ -12,10 +12,14 @@
...
-}
+public enum StorageFragmentPurpose {
+    SLOAD_DOING,
+    SLOAD_UNDOING,
+
+    SSTORE_DOING,
+    SSTORE_UNDOING,
+
+    PRE_WARMING
+};
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/storage/StorageFragmentPurpose.java:25]: Mostly for debugging, though we may want to do this more generally: have a system whereby we can tag / label rows (i.e. fragments) with auxiliary information such as
- hub stamp (if not accessible other wise)
- instruction
- "purpose" of the row

The `purpose` business will be useful for debugging CALL's etc ... anything with many rows with complex purposes.

Another tagging we should have present is to tag a `CallFrame` according to whether it was created by
- `CALL` / `STATICCALL`
- `DELEGATECALL` / `CALLCODE`
- `CREATE` / `CREATE2`

The distinction MESSAGE_CALL / CONTRACT_CREATION is too coarse, that is: we must refine the MESSAGE_CALL category

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/SloadSection.java [hunk 22]
```diff
@@ -43,23 +46,23 @@ public class SloadSection extends TraceSection implements PostRollbackDefer {
...
-    this.exceptions = hub.pch().exceptions();
+    world = worldView;
+    address = hub.messageFrame().getRecipientAddress();
+    deploymentNumber = hub.deploymentNumberOf(address);
+    storageKey = Bytes32.leftPad(hub.messageFrame().getStackItem(0));
+    incomingWarmth = hub.messageFrame().getWarmedUpStorage().contains(address, storageKey);
+    valueOriginal =
+        EWord.of(worldView.get(address).getOriginalStorageValue(UInt256.fromBytes(storageKey)));
+    valueCurrent = EWord.of(worldView.get(address).getStorageValue(UInt256.fromBytes(storageKey)));
+    exceptions = hub.pch().exceptions();
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/SloadSection.java:67]: The disparity between the underlying addresses (accountAddress vs bytecodeAddress) seems to have caused the above.

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/SstoreSection.java [hunk 23]
```diff
@@ -46,21 +49,21 @@ public class SstoreSection extends TraceSection implements PostRollbackDefer {
...
-    this.valueNext = EWord.of(hub.messageFrame().getStackItem(1));
+    world = worldView;
+    address = hub.messageFrame().getRecipientAddress();
+    deploymentNumber = hub.deploymentNumberOf(address);
+    storageKey = Bytes32.leftPad(hub.messageFrame().getStackItem(0));
+    incomingWarmth = hub.messageFrame().getWarmedUpStorage().contains(address, storageKey);
+    valueOriginal =
+        EWord.of(worldView.get(address).getOriginalStorageValue(UInt256.fromBytes(storageKey)));
+    valueCurrent = EWord.of(worldView.get(address).getStorageValue(UInt256.fromBytes(storageKey)));
+    valueNext = EWord.of(hub.messageFrame().getStackItem(1));
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/SstoreSection.java:68]: Same remark about the `address of the underlying account` vs `address whose code is currently executing`.

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java (hunk 1 above)
Comment (OlivierBBB) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java:662]: **This method seems to be failing on some tests ...**

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/AccountSnapshot.java [hunk 24]
```diff
@@ -42,56 +43,61 @@ public class AccountSnapshot {
...
-        "Insufficient balance\n     Address: %s\n     Balance: %s\n     Value: %s"
-            .formatted(this.address, this.balance, quantity));
-    this.balance = this.balance.subtract(quantity);
-    return this;
-  }
-
-  public AccountSnapshot incrementBalance(Wei quantity) {
-    this.balance = this.balance.add(quantity);
-    return this;
+  public static AccountSnapshot canonical(
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/AccountSnapshot.java:64]: What's the purpose of this ? We already have a `canonical` that does the same, wo the world in the signature, using `hub.messageFrame().getWorldUpdater()`

Comment (letypequividelespoubelles) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/AccountSnapshot.java:64]: oh my bad, I remember we use it in startTx where we don't have the world through the frame

Comment (letypequividelespoubelles) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/AccountSnapshot.java:64]: anyway, we should merge the two method

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/AccountSnapshot.java [hunk 25]
```diff
@@ -128,87 +134,101 @@ public static AccountSnapshot fromAccount(
...
+   * @param quantity
+   * @return {@code this} with decremented balance
+   */
+  public AccountSnapshot decrementBalanceBy(Wei quantity) {
+    Preconditions.checkState(
+        this.balance.greaterOrEqualThan(quantity),
+        "Insufficient balance\n     Address: %s\n     Balance: %s\n     Value: %s"
+            .formatted(this.address, this.balance, quantity));
+
+    this.balance = this.balance.subtract(quantity);
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/AccountSnapshot.java]: so we keep `this` ? ;)

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java [hunk 26]
```diff
@@ -484,6 +485,8 @@ public void traceStartTransaction(final WorldView world, final Transaction tx) {
     state.enter();
     txStack.enterTransaction(world, tx, transients.block());
 
+    defers.scheduleForPostTransaction(txStack.current());
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java:488]: what's the purpose of this ?

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/storage/StorageFragment.java (hunk 20 above)
Comment (letypequividelespoubelles) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/storage/StorageFragment.java:58]: still here ?

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/CreateSection.java [hunk 27]
```diff
@@ -214,6 +214,7 @@ public CreateSection(Hub hub) {
             this, hub.currentFrame()); // To get the success bit of the CREATE(2)
 
     hub.romLex().callRomLex(frame);
+    // hub.transients().conflation().deploymentInfo().newDeploymentAt(createeAddress);
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/CreateSection.java]: ?

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxFinalizationSection.java [hunk 28]
```diff
@@ -30,202 +33,250 @@
...
-            depInfo.isDeploying(minerAddress));
+    final Address recipientAddress = txMetadata.getEffectiveRecipient();
+    final Address coinbaseAddress = txMetadata.getCoinbase();
+
+    // recipient
+    senderSnapshotBeforeFinalization = AccountSnapshot.canonical(hub, senderAddress);
+    recipientSnapshotBeforeFinalization = AccountSnapshot.canonical(hub, recipientAddress);
+    coinbaseSnapshotBeforeTxFinalization = AccountSnapshot.canonical(hub, coinbaseAddress);
+
+    //  TODO: re-enable checks
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxFinalizationSection.java:56]: are the checks creatuing java exfeption ?

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxSkippedSection.java [hunk 29]
```diff
@@ -46,93 +47,106 @@ public TxSkippedSection(
...
-                newToAccount,
-                DomSubStampsSubFragment.standardDomSubStamps(hub.stamp(), 1)));
+                recipientAccountSnapshotBefore,
+                recipientAccountSnapshotAfter,
+                DomSubStampsSubFragment.standardDomSubStamps(hub.stamp(), 1));
 
-    // Miner
-    this.addFragment(
+    // coinbase account fragment
+    AccountFragment coinbaseAccountFragment =
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxSkippedSection.java]: all fragments could be final

**Review by letypequividelespoubelles — APPROVED** [review]
LGTM

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/AccountSnapshot.java (hunk 24 above)
Comment (OlivierBBB) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/AccountSnapshot.java:64]: > I remember we use it in startTx where we don't have the world through the frame

It's for that kind of reason. We don't have access to the `MessageFrame` at certain points in time but we do have access to some `WorldView` or so.

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/CreateSection.java (hunk 27 above)
Comment (OlivierBBB) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/CreateSection.java]: I took it out here as it's already done at `traceContextEnter` in `Hub.java` so this would be doing it twice

image

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxFinalizationSection.java (hunk 28 above)
Comment (OlivierBBB) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxFinalizationSection.java:56]: Yes, they were last time I checked

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxSkippedSection.java (hunk 29 above)
Comment (OlivierBBB) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxSkippedSection.java]: Done

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/AccountSnapshot.java (hunk 24 above)
Comment (letypequividelespoubelles) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/AccountSnapshot.java:64]: Still they should both call the same method with account hub and address to not duplicate the underlying constructor with if null etc

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/AccountSnapshot.java (hunk 25 above)
Comment (OlivierBBB) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/AccountSnapshot.java]: Done

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/CreateSection.java (hunk 27 above)
Comment (letypequividelespoubelles) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/CreateSection.java]: OK maybe add a dic comment to explain it ?

Comment (OlivierBBB) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/CreateSection.java]: I removed it altogether (the comment.)

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/AccountSnapshot.java (hunk 24 above)
Comment (OlivierBBB) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/AccountSnapshot.java:64]: Yeah I agree.

Comment (OlivierBBB) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/AccountSnapshot.java:64]: Done
