### PR TITLE
fix(OOB_CALL): confusion between call and callee gas for BLAKE

### LINKED ISSUE #1362: Failing OobCall during a BLAKE2F call
ref test 201

### PR DESCRIPTION
**Pull request by letypequividelespoubelles**

### CODE REVIEW

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/imc/oob/precompiles/Blake2fParamsOobCall.java [hunk 1]
```diff
@@ -63,7 +62,7 @@ public Trace trace(Trace trace) {
     return trace
         .pMiscOobFlag(true)
         .pMiscOobInst(oobInstructionValue())
-        .pMiscOobData1(bigIntegerToBytes(callGas))
+        .pMiscOobData1(bigIntegerToBytes(calleeGas))
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/imc/oob/precompiles/Blake2fParamsOobCall.java:65]: OK

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/oob/OobOperation.java [hunk 2]
```diff
@@ -314,7 +315,7 @@ public void populateColumnsForPrecompile(MessageFrame frame) {
       calleeGas = ((ModexpPricingOobCall) oobCall).getCallGas();
     }
     if (oobCall instanceof Blake2fParamsOobCall) {
-      calleeGas = ((Blake2fParamsOobCall) oobCall).getCallGas();
+      calleeGas = ((Blake2fParamsOobCall) oobCall).getCalleeGas();
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/oob/OobOperation.java:318]: OK

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/imc/ImcFragment.java [hunk 3]
```diff
@@ -68,9 +66,6 @@ public static ImcFragment forTxInit(final Hub hub) {
     // isdeployment == false
     // non empty calldata
     final TransactionProcessingMetadata currentTx = hub.txStack().current();
-    final boolean isMessageCallTransaction = currentTx.getBesuTransaction().getTo().isPresent();
-
-    final Optional<Bytes> txData = currentTx.getBesuTransaction().getData();
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/imc/ImcFragment.java:73]: OK

**Review by OlivierBBB — APPROVED** [review]
LGTM

**Review by lorenzogentile404 — APPROVED** [review]
LGTM
