### PR TITLE
Leo's new ranges

### LINKED ISSUE #1046: logs for the first range: 5118361-5118389 (exitDeploymentFromDeploymentInfoPointOfView)
## Ranges

```rust
5118361-5118389
```

## Issue

              logs for the first range: 5118361-5118389

07:33:03.621 [vert.x-worker-thread-5] ERROR net.consensys.linea.zktracer.ZkTracer - First exception that was caught while tracing:
java.lang.IllegalArgumentException: null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:129) ~[guava-33.0.0-jre.jar:?]
        at net.consensys.linea.zktracer.module.hub.Hub.exitDeploymentFromDeploymentInfoPointOfView(Hub.java:714) ~[?:?]
        at net.consensys.linea.zktracer.module.hub.Hub.traceContextExit(Hub.java:662) ~[?:?]
        at net.consensys.linea.zktracer.ZkTracer.traceContextExit(ZkTracer.java:311) ~[?:?]
        at org.hyperledger.besu.evm.processor.AbstractMessageProcessor.process(AbstractMessageProcessor.java:219) ~[besu-evm-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.process(MainnetTransactionProcessor.java:607) ~[besu-core-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.processTransaction(MainnetTransactionProcessor.java:457) ~[besu-core-24.8-develop-dce796c.jar:24.8-develop-dce796c]
        at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.processTransaction(MainnetTransactionProcessor.java:229) ~[besu-core-24.8-develop-dce796c.jar:24.8-develop-dce796c]

_Originally posted by @FlorianHuc in https://github.com/Consensys/linea-tracer/issues/1043#issuecomment-2320349590_

### PR DESCRIPTION
**Pull request by OlivierBBB**

### CODE REVIEW

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java [hunk 1]
```diff
@@ -711,9 +711,27 @@ public void traceContextExit(MessageFrame frame) {
...
+       * skipped (empty bytecode) i.e. that are in the TX_SKIP phase immediately transition to "the
+       * deployed state"/
+       */
+      Preconditions.checkArgument(!deploymentStatusOfBytecodeAddress());
+    }
+
     Preconditions.checkArgument(
-        deploymentStatusOfBytecodeAddress()
-            == (messageFrame().getType() == MessageFrame.Type.CONTRACT_CREATION));
+        this.currentFrame().byteCodeAddress().equals(this.bytecodeAddress()));
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java]: I was using `==` rather than `.equals`

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java [hunk 2]
```diff
@@ -711,9 +711,27 @@ public void traceContextExit(MessageFrame frame) {
...
+              this.opCode()));
+    } else {
+      /**
+       * EXPLANATION: the deployment addresses associated with deployment transactions that get
+       * skipped (empty bytecode) i.e. that are in the TX_SKIP phase immediately transition to "the
+       * deployed state"/
+       */
+      Preconditions.checkArgument(!deploymentStatusOfBytecodeAddress());
+    }
+
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java:752]: The only subtle point

File: ranges_file.txt [hunk 3]
```diff
@@ -0,0 +1,194 @@
+5389571-5389577
```
Comment (letypequividelespoubelles) [inline ranges_file.txt:1]: Do we need to keep it ?

And for all replay json, if they all crashed the same error, maybe keep only one?

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java [hunk 4]
```diff
@@ -711,9 +711,27 @@ public void traceContextExit(MessageFrame frame) {
   private void exitDeploymentFromDeploymentInfoPointOfView() {
 
     // sanity check
+    if (this.state.processingPhase != TX_SKIP) {
+      Preconditions.checkArgument(
+          deploymentStatusOfBytecodeAddress()
+              == (messageFrame().getType() == MessageFrame.Type.CONTRACT_CREATION),
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java]: .equals ?

**Review by letypequividelespoubelles — APPROVED** [review]

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java (hunk 4 above)
Comment (OlivierBBB) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java]: It's an `enum` comparison, no `.equals(...)` required.

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java [hunk 5]
```diff
@@ -301,12 +302,16 @@ private List<Module> precompileLimitModules() {
   /** reference table modules */
   private final List<Module> refTableModules;
 
+  /** fix this mess */
+  public boolean failureCondition_ArnoldPalmerAlert_ArnoldPalmerAlert_WhoWantsSomeArniePalmies =
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java]: WTF ?

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java [hunk 6]
```diff
@@ -620,29 +619,31 @@ public void traceContextEnter(MessageFrame frame) {
...
-      final long callDataContextNumber = this.callStack.current().contextNumber();
+      final long callDataContextNumber = callStack.current().contextNumber();
 
-      this.callStack.enter(
-          this.state.stamps().hub(),
-          frame.getRecipientAddress(),
-          frame.getContractAddress(),
-          frame.getRecipientAddress(), // TODO: this is likely false
-          new Bytecode(frame.getCode().getBytes()),
+      // TODO: the
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java]: ?

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java [hunk 7]
```diff
@@ -620,29 +619,31 @@ public void traceContextEnter(MessageFrame frame) {
...
+          new Bytecode(frame.getCode().getBytes()),
+          frame.getSenderAddress(), // TODO: is this better ?
           frame.getInputData(),
           callDataOffset,
           callDataSize,
-          callDataContextNumber,
-          this.transients.conflation().deploymentInfo().deploymentNumber(codeAddress),
-          codeDeploymentNumber,
-          isDeployment);
-      this.currentFrame().initializeFrame(frame); // TODO should be done in enter
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java:645]: // TODO should be done in enter

because we do it both if depth == 0 and if depth > 0

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java [hunk 8]
```diff
@@ -685,35 +686,81 @@ public void traceContextExit(MessageFrame frame) {
...
+        } else {
+          // non failure condition
+          checkArgument(
+              deploymentStatusOfBytecodeAddress()
+                  == !messageFrame().getCode().getBytes().isEmpty());
+        }
+      } else {
+        checkArgument(!deploymentStatusOfBytecodeAddress());
+      }
+      // checkArgument(
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java]: comment to delete

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java [hunk 9]
```diff
@@ -806,25 +849,25 @@ public void tracePostExecution(MessageFrame frame, Operation.OperationResult ope
...
-
   public int getCfiByMetaData(
       final Address address, final int deploymentNumber, final boolean deploymentStatus) {
     return this.romLex()
         .getCodeFragmentIndexByMetadata(
             ContractMetadata.make(address, deploymentNumber, deploymentStatus));
   }
 
+  public int callDataContextNumber(final boolean shouldCopyTxCallData) {
+    return shouldCopyTxCallData ? this.stamp() : 0;
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java:861]: is this boolean still needed ? I recall we finally create a callFrame for the tx callData, even if it's empty, n the case someone does a CALLDATACOPY, we need to have in the callFrame list (I fixed this in a past replayTest imho ...)

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/romlex/RomLex.java [hunk 10]
```diff
@@ -120,15 +116,18 @@ public Bytes getCodeByMetadata(final ContractMetadata metadata) {
     return getChunkByMetadata(metadata).map(RomChunk::byteCode).orElse(Bytes.EMPTY);
   }
 
+  // TODO: it would maybe make more sense to only implement traceContextEnter
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/romlex/RomLex.java:124]: hum ... not sure. Because when we enter a context, ROMLEX is triggered by the call / create section. Here ROMLEX is triggered by the Besu hook, so it's quite different.

File: arithmetization/src/test/java/net/consensys/linea/zktracer/ReplayTests.java [hunk 11]
```diff
@@ -199,84 +203,346 @@ void replayMultipleReplayFiles() {
...
   }
 
+  // @Disabled
   @Test
   void blockHash1() {
-    replay("8718090.json.gz");
+    replay("8718090.json.gz", false);
   }
 
+  // @Disabled
```
Comment (letypequividelespoubelles) [inline arithmetization/src/test/java/net/consensys/linea/zktracer/ReplayTests.java:274]: why all teg @Disabled are commented ? Better delete them no ?

File: arithmetization/src/test/java/net/consensys/linea/zktracer/ReplayTests.java [hunk 12]
```diff
@@ -199,84 +203,346 @@ void replayMultipleReplayFiles() {
...
   }
 
   // TODO: should be replaced by a unit test triggering a failed CREATE2
   @Test
   void failedCreate2() {
-    replay("41640-41649.json.gz");
+    replay("41640-41649.json.gz", false);
+  }
+
+  // Leo's range split up 5104800-5104883
```
Comment (letypequividelespoubelles) [inline arithmetization/src/test/java/net/consensys/linea/zktracer/ReplayTests.java:299]: could be nice to have a descriptive name of the test to know what was the issue, and let us have the possibility to run unit test to reduce the nb of replay tests. CI will be too long if not ...

File: testing/src/main/java/net/consensys/linea/testing/ToyExecutionEnvironmentV2.java [hunk 13]
```diff
@@ -147,7 +147,7 @@ private MainnetTransactionProcessor getMainnetTransactionProcessor(EVM evm) {
         new MessageCallProcessor(evm, precompileContractRegistry);
 
     final ContractCreationProcessor contractCreationProcessor =
-        new ContractCreationProcessor(evm, false, List.of(), 0);
+        new ContractCreationProcessor(evm, false, List.of(), 1);
```
Comment (letypequividelespoubelles) [inline testing/src/main/java/net/consensys/linea/testing/ToyExecutionEnvironmentV2.java:150]: What's the impact ?

**Review by letypequividelespoubelles — CHANGES_REQUESTED** [review]

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java (hunk 5 above)
Comment (OlivierBBB) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java]: What's wrong? I blame Copilot 😎

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java (hunk 7 above)
Comment (OlivierBBB) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java:645]: I tried doing it for once for both but it breaks even our tests. I think it's related to entering the modules.

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java (hunk 9 above)
Comment (OlivierBBB) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java:861]: We will not be copying zeros from an empty calldata array. It's done without reference to any context

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java (hunk 7 above)
Comment (OlivierBBB) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/Hub.java:645]: I tried doing it for once for both but it breaks even our tests. I think it's related to entering the modules.@

File: arithmetization/src/test/java/net/consensys/linea/zktracer/ReplayTests.java (hunk 11 above)
Comment (OlivierBBB) [reply arithmetization/src/test/java/net/consensys/linea/zktracer/ReplayTests.java:274]: It's just easier to uncomment them again when they are already in the file. Running the full tests (with the replays) take 2.5 hours.

File: testing/src/main/java/net/consensys/linea/testing/ToyExecutionEnvironmentV2.java (hunk 13 above)
Comment (OlivierBBB) [reply testing/src/main/java/net/consensys/linea/testing/ToyExecutionEnvironmentV2.java:150]: It was first noticed by @davepearce. It means that accounts created start out with a nonce of 1 (as in the EVM since some old hard fork) as opposed to an initial value of 0 (as was the case prior to said hardfork.)

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/romlex/ContractMetadata.java [hunk 14]
```diff
@@ -25,15 +26,16 @@
  * @param underDeployment whether this contract is being deployed
  */
 public record ContractMetadata(Address address, int deploymentNumber, boolean underDeployment) {
+  public static ContractMetadata canonical(Hub hub, Address address) {
+    return new ContractMetadata(
+        address, hub.deploymentNumberOf(address), hub.deploymentStatusOf(address));
+  }
+
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/romlex/ContractMetadata.java:33]: `canonical` should become the preferred method for creating `ContractMetadata`

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/romlex/ContractMetadata.java [hunk 15]
```diff
@@ -25,15 +26,16 @@
...
   public static ContractMetadata make(
       final Address address, int deploymentNumber, boolean underDeployment) {
     return new ContractMetadata(address, deploymentNumber, underDeployment);
   }
 
-  public static ContractMetadata deployed(final Address address, int deploymentNumber) {
-    return new ContractMetadata(address, deploymentNumber, false);
-  }
-
   public static ContractMetadata underDeployment(final Address address, int deploymentNumber) {
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/romlex/ContractMetadata.java:39]: Can we get rid of `underDeployment` by deferring it ?

File: ranges_file.txt (hunk 3 above)
Comment (OlivierBBB) [reply ranges_file.txt:1]: We don't need this file, I will delete it.

Comment (OlivierBBB) [reply ranges_file.txt:1]: I will delete it later, it's something I discussed with @gusiri (the ability to provide custom `ranges.csv` files)

File: arithmetization/src/test/java/net/consensys/linea/zktracer/ReplayTests.java (hunk 12 above)
Comment (OlivierBBB) [reply arithmetization/src/test/java/net/consensys/linea/zktracer/ReplayTests.java:299]: Let me see what I can do.

**Review by letypequividelespoubelles — APPROVED** [review]
