### PR TITLE
fix(mmu): anyToRamWithPadding mixed subcase

### LINKED ISSUE #1005: range 6029454  6029459
## Ranges

```rust
6029454-6029459
```

## Issue

ime curl --location --request POST 'localhost:15480' --header 'Content-Type: application/json' --data-raw '{"jsonrpc": "2.0", "method": "linea_generateConflatedTracesToFileV2", "params": [{"startBlockNumber": 6029454 , "endBlockNumber":6029459 , "expectedTracesEngineVersion": "0.5.0-beta"}], "id": 1}'
{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"Plugin internal error","data":"Illegal Capacity: -212"}}
error:
  private List<RowTypeRecord> generateRowTypeList() {
    final int totInit = mmuData().numberMmioInstructions();
    List<RowTypeRecord> output = new ArrayList<>(totInit);
totInit is negative.

### PR DESCRIPTION
**Pull request by letypequividelespoubelles**

### CODE REVIEW

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmu/instructions/AnyToRamWithPadding.java [hunk 1]
```diff
@@ -230,10 +230,7 @@ private void sharedRow2(final HubToMmuValues hubToMmuValues) {
     if (mixed) {
       transferSize =
           (hubToMmuValues.referenceSize() - hubToMmuValues.sourceOffsetLo().longValueExact());
-      paddingSize =
-          (hubToMmuValues.size()
-              - (hubToMmuValues.referenceSize()
-                  - hubToMmuValues.sourceOffsetLo().longValueExact()));
+      paddingSize = (hubToMmuValues.size() - transferSize);
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmu/instructions/AnyToRamWithPadding.java:233]: Was that a bug ? (Sign issue I mean)

**Review by OlivierBBB — APPROVED** [review]

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmu/instructions/AnyToRamWithPadding.java (hunk 1 above)
Comment (letypequividelespoubelles) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmu/instructions/AnyToRamWithPadding.java:233]: no, just a simplification as `transferSize = (hubToMmuValues.referenceSize()
                  - hubToMmuValues.sourceOffsetLo().longValueExact())`
