### PR TITLE
fix: loosen requirements to count EcData.callEcData()

### LINKED ISSUE #2383: fix: `ZkCounter` for `EcData.callEcData()`
The conditions for when calls to `EcData.callEcData()` are counted in `ZkCounter` look to be too restrictive.

### PR DESCRIPTION
**Pull request by DavePearce**
This loosens the requirements for counting an `EcData.callEcData()` call for the ECRECOVER, ECADD and ECMUL cases.

---

> [!NOTE]
> Count EC precompile `EcData` calls on any non-empty input (regardless of success) and document MXP ctMax-to-line-count conversion.
> 
> - **zktracer**:
>   - `ZkCounter.tracePrecompileCall`: invoke `EcData.callEcData(...)` for `PRC_ECRECOVER`, `PRC_ECADD`, `PRC_ECMUL` whenever call data is non-empty (no longer requires `COMPLETED_SUCCESS`).
> - **Docs**:
>   - Add detailed Javadoc explaining `CancunMxpOperation.MXP_FROM_CTMAX_TO_LINECOUNT` and its role in converting `ctMax` to full MXP line count.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 90b6c546b0ab8003eb9d83fc688157276ee533b2. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: arithmetization/src/main/java/net/consensys/linea/zktracer/ZkCounter.java [hunk 1]
```diff
@@ -695,7 +695,7 @@ public void tracePrecompileCall(MessageFrame frame, long gasRequirement, Bytes o
     switch (precompile) {
       case PRC_ECRECOVER, PRC_ECADD, PRC_ECMUL -> {
         // trigger EcData to count the underlying EC operations
-        if (prcSuccess && callDataSize != 0) {
+        if (callDataSize != 0) {
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/ZkCounter.java:698]: We for sure don't want to make the EC_DATA call conditional to `prcSuccess` where
```java
final boolean prcSuccess = frame.getState() == COMPLETED_SUCCESS;
```
So removing it is correct.

**Review by OlivierBBB — APPROVED** [review]
LGTM
