### PR TITLE
fix(romlex): first account is already deployed and at address 0

### LINKED ISSUE #1869: fix(romlex): blockchain ref tests CFI lex ordering

### PR DESCRIPTION
**Pull request by letypequividelespoubelles**

### CODE REVIEW

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/transients/Conflation.java [hunk 1]
```diff
@@ -32,9 +32,4 @@ public class Conflation {
       new StackedSet<>(256, 32);
   private final StackedSet<StackHeightCheck> stackHeightChecksForStackOverflows =
       new StackedSet<>(256, 32);
-
-  public int log(LogData logData) {
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/transients/Conflation.java:36]: dead code

**Review by DavePearce — APPROVED** [review]
LGTM

File: .github/actions/setup-go-corset/action.yml [hunk 2]
```diff
@@ -9,4 +9,4 @@ runs:
 
     - name: Install Go Corset
       shell: bash
-      run: go install github.com/consensys/go-corset/cmd/go-corset@v0.9.4
+      run: go install github.com/consensys/go-corset/cmd/go-corset@12a62d2
```
Comment (amkCha) [inline .github/actions/setup-go-corset/action.yml]: You can maybe put 1.0.0 now ?

File: arithmetization/src/test/java/net/consensys/linea/zktracer/module/romlex/FirstCfiAccountIsZeroTests.java [hunk 3]
```diff
@@ -0,0 +1,81 @@
...
+import org.hyperledger.besu.datatypes.Address;
+import org.hyperledger.besu.datatypes.Hash;
+import org.hyperledger.besu.datatypes.Wei;
+import org.hyperledger.besu.ethereum.core.Transaction;
+import org.junit.jupiter.api.Test;
+
+public class FirstCfiAccountIsZeroTests {
+  /**
+   * This test checks that the strict lexicographic order of the ROM_LEX is working when the account
+   * with CFI has Address 0, Deployment number 0 and deployment status 0.
```
Comment (amkCha) [inline arithmetization/src/test/java/net/consensys/linea/zktracer/module/romlex/FirstCfiAccountIsZeroTests.java:39]: What does deployment status 0 mean ?

File: .github/actions/setup-go-corset/action.yml (hunk 2 above)
Comment (letypequividelespoubelles) [reply .github/actions/setup-go-corset/action.yml]: yes, absolutely

File: arithmetization/src/test/java/net/consensys/linea/zktracer/module/romlex/FirstCfiAccountIsZeroTests.java (hunk 3 above)
Comment (letypequividelespoubelles) [reply arithmetization/src/test/java/net/consensys/linea/zktracer/module/romlex/FirstCfiAccountIsZeroTests.java:39]: That's what made the first arithmetization of the HUB crashed on mainnet launch :)

When you deploy a SMC, in the arithmetization, its dep number is set to ++1. So that you discriminate the underlying SMC if you deploy, selfdestruct, and then redeploy again. 
The dep status is to discriminate between the initcode of the SMC deployment, and its deployed code.
