### PR TITLE
fix(shfreftable): turned MSHP into an UnsignedByte

### LINKED ISSUE #725: fix(shfreftable): regenerate Trace.java since MSHP column is 16 bits while in constraints is 8 bits only

### PR DESCRIPTION
**Pull request by lorenzogentile404**

### CODE REVIEW

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/tables/shf/Trace.java [hunk 1]
```diff
@@ -184,7 +184,7 @@ public Trace fillAndValidateRow() {
     }
 
     if (!filled.get(3)) {
-      mshp.position(mshp.position() + 2);
+      mshp.position(mshp.position() + 1);
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/tables/shf/Trace.java:187]: What does this do ?
I imagine that the 2 -> 1 here is the same as the 2 -> 1 change in the ColumnHeader for MSHP ?

**Review by OlivierBBB — APPROVED** [review]
Downstream changes from having µMSHP going from `:i8` to `:byte` in the lisp. LGTM.
Also see https://github.com/Consensys/corset/issues/158

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/tables/shf/Trace.java (hunk 1 above)
Comment (letypequividelespoubelles) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/tables/shf/Trace.java:187]: yes, its is. Generated by corset.

**Review by letypequividelespoubelles — APPROVED** [review]
