### PR TITLE
fix: bit decomposition for small r s for legacy rlptxn

### LINKED ISSUE #2229: small R / S constraint error in legacy RlpTxn

### PR DESCRIPTION
**Pull request by letypequividelespoubelles**

### CODE REVIEW

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/rlptxn/london/LondonRlpTxn.java [hunk 1]
```diff
@@ -734,7 +734,7 @@ private void handle32BytesInteger(
       if (inputLen <= traceValue.nStep) {
         ByteCountAndPowerOutput byteCountingOutput = byteCounting(inputLen, traceValue.nStep);
         BitDecOutput bitDecOutput =
-            bitDecomposition(inputByte.get(inputByte.size() - 1), traceValue.nStep);
+            bitDecomposition((0xFF & inputByte.get(inputByte.size() - 1)), traceValue.nStep);
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/rlptxn/london/LondonRlpTxn.java:737]: this is the fix

**Review by DavePearce — APPROVED** [review]
LGTM
