### PR TITLE
fix(cancun): dom stamp in hub tx skip section

### LINKED ISSUE #2172: fix TX_SKIP hub section in cancun

### PR DESCRIPTION
**Pull request by letypequividelespoubelles**

### CODE REVIEW

File: testing/src/main/java/net/consensys/linea/reporting/TracerTestBase.java [hunk 1]
```diff
@@ -30,7 +30,7 @@ public class TracerTestBase {
   @BeforeEach
   public void init(TestInfo testInfo) {
       TracerTestBase.testInfo.chainConfig =
-              switch (getForkOrDefault("LONDON")) {
+              switch (getForkOrDefault("CANCUN")) {
```
Comment (DavePearce) [inline testing/src/main/java/net/consensys/linea/reporting/TracerTestBase.java]: Is this intentional?

File: arithmetization/src/main/java/net/consensys/linea/corset/CorsetValidator.java [hunk 2]
```diff
@@ -137,7 +137,7 @@ private List<String> buildCommandLine(Path traceFile, String zkEvmBin) {
     ArrayList<String> options = new ArrayList<>();
     // Determine options to use (either default or override)
     String flags =
-        System.getenv().getOrDefault("GOCORSET_FLAGS", "--report --report-context 2 --mir ");
+        System.getenv().getOrDefault("GOCORSET_FLAGS", "--report --report-context 2 --air ");
```
Comment (DavePearce) [inline arithmetization/src/main/java/net/consensys/linea/corset/CorsetValidator.java:140]: Using `--air` is more accurate, but could have performance impacts when running on local machines.

**Review by DavePearce — APPROVED** [review]
LGTM --- some comments noted.
