### PR TITLE
Fix for `BLOCKHASH` conversion error

### LINKED ISSUE #1024: Prevent Conversion Error for `BLOCKHASH` in `BlockCapturer`
Currently we have this in `BlockCapturer.java`:

```
case BLOCKHASH -> {
        if (frame.stackSize() > 0) {
          BigInteger peek0 = frame.getStackItem(0).toUnsignedBigInteger();
          // Determine block number requested
          final long blockNumber = peek0.longValueExact();
          // Use enclosing frame to determine hash
          Hash blockHash = frame.getBlockHashLookup().apply(blockNumber);
          // Record it was seen
          this.reaper.touchBlockHash(blockNumber, blockHash);
        }
      }
```

However, there is a risk that the conversion `longValueExact()` could fail in the event someone uses a large (invalid) block number as the argument.  That is permitted and, in this case, the EVM places are `0` on the stack.  Therefore, we should catch the case where there is a conversion error and ignore it (i.e. no need to touch the block hash in this case).

Thanks to @letypequividelespoubelles for spotting this problem!

### PR DESCRIPTION
**Pull request by DavePearce**
This puts in place a simple fix for ensuring captured block hashes are for valid blocks relative to the current block.  This is based on the implementation in [BlockHashOperation.java](https://github.com/Consensys/linea-besu/blob/zkbesu/evm/src/main/java/org/hyperledger/besu/evm/operation/BlockHashOperation.java)

### CODE REVIEW

File: arithmetization/src/main/java/net/consensys/linea/blockcapture/BlockCapturer.java [hunk 1]
```diff
@@ -39,6 +38,10 @@
 import org.hyperledger.besu.plugin.data.BlockHeader;
 
 public class BlockCapturer implements ConflationAwareOperationTracer {
+  public static final int MAX_RELATIVE_BLOCK = 256;
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/blockcapture/BlockCapturer.java:41]: you could use `BLOCKHASH_MAX_HISTORY` in `GlobalConstants.java`

**Review by letypequividelespoubelles — APPROVED** [review]
LGTM

File: arithmetization/src/main/java/net/consensys/linea/blockcapture/BlockCapturer.java (hunk 1 above)
Comment (DavePearce) [reply arithmetization/src/main/java/net/consensys/linea/blockcapture/BlockCapturer.java:41]: Well maybe at some point I'll put that in
