### PR TITLE
test: extend INVALID opcode

### LINKED ISSUE #1643: test: `INVALID` opcode
Extend [https://github.com/Consensys/linea-tracer/blob/arith-dev/arithmetization/src/test/[…]ensys/linea/zktracer/exceptions/InvalidOpcodeExceptionTest.java](https://github.com/Consensys/linea-tracer/blob/arith-dev/arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/InvalidOpcodeExceptionTest.java).

### PR DESCRIPTION
**Pull request by lorenzogentile404**

### CODE REVIEW

File: arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/InvalidOpcodeExceptionTest.java [hunk 1]
```diff
@@ -37,4 +44,28 @@ void invalidOpcodeExceptionTest() {
...
+  static Stream<Arguments> nonOpcodeExceptionSource() {
+    List<Arguments> arguments = new ArrayList<>();
+    for (int value = 0; value < 256; value++) {
+      OpCode opCode = OpCode.of(value);
+      // If the value is not a valid opcode, the corresponding value is used in the test
+      if (opCode == OpCode.INVALID) {
+        arguments.add(Arguments.of(value));
+      }
+    }
+    return arguments.stream();
```
Comment (OlivierBBB) [inline arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/InvalidOpcodeExceptionTest.java:69]: Won't that just retain precisely the INVALID opcode ?

Comment (OlivierBBB) [reply arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/InvalidOpcodeExceptionTest.java:69]: I would expect that you have to go through the Invalid `InstructionFamily`

Comment (OlivierBBB) [reply arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/InvalidOpcodeExceptionTest.java:69]: I guess it depends on the implementation of `OpCode.of( ... )`. I did touch related functions recently. I guess it would have to be tested.

Comment (OlivierBBB) [reply arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/InvalidOpcodeExceptionTest.java:69]: My bad, it works

image

Comment (lorenzogentile404) [reply arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/InvalidOpcodeExceptionTest.java:69]: Exactly, I replied to your comment on Slack. I'll add a comment to make it clear.

Comment (lorenzogentile404) [reply arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/InvalidOpcodeExceptionTest.java:69]: I used another approach that makes it more explicit what is happening using:

```
 static Stream<Arguments> nonOpcodeExceptionSource() {
    List<Arguments> arguments = new ArrayList<>();
    for (int value = 0; value < 256; value++) {
      // If value it not in the map, then it is not an OpCode
      if (!valueToOpCodeDataMap.containsKey(value)) {
        arguments.add(Arguments.of(value));
      }
    }
    return arguments.stream();
  }
```

**Review by OlivierBBB — APPROVED** [review]
