### PR TITLE
Encapsulate in `try/catch` reference tests failing due to BLS precompiles

### LINKED ISSUE #2313: Encapsulate in `try/catch` reference tests failing due to BLS precompiles

### PR DESCRIPTION
**Pull request by lorenzogentile404**

### CODE REVIEW

File: reference-tests/src/test/java/net/consensys/linea/BlockchainReferenceTestTools.java [hunk 1]
```diff
@@ -638,6 +640,10 @@ public static void executeTest(final BlockchainReferenceTestCaseSpec spec) {
       } catch (final RLPException e) {
         log.info("caught RLP exception, checking it's invalid {}", candidateBlock.isValid());
         assertThat(candidateBlock.isValid()).isFalse();
+      } catch (Exception e) {
+        // Tmp: we ignore this error, as BLS precompiles are excluded in prod, but not in test
+        checkArgument(
+            e.getMessage().contains(ERROR_MESSAGE_TRIED_TO_COMMIT_UNPROVABLE_TX), e.getMessage());
```
Comment (OlivierBBB) [inline reference-tests/src/test/java/net/consensys/linea/BlockchainReferenceTestTools.java]: Do we have the certainty that this will only catch limits related exceptions ?

Comment (letypequividelespoubelles) [reply reference-tests/src/test/java/net/consensys/linea/BlockchainReferenceTestTools.java]: yes

**Review by letypequividelespoubelles — APPROVED** [review]
