### PR TITLE
Fixing issues with column sizes

### LINKED ISSUE #1392: Fixing issues with column sizes

### PR DESCRIPTION
**Pull request by OlivierBBB**

### CODE REVIEW

File: arithmetization/src/main/java/net/consensys/linea/zktracer/opcode/OpCodeData.java [hunk 1]
```diff
@@ -77,6 +77,14 @@ public boolean isHalt() {
     return this.instructionFamily == InstructionFamily.HALT;
   }
 
+  public boolean isCall() {
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/opcode/OpCodeData.java:88]: We already have those method somewhere else (based on the opcode, not the opcode family)

Comment (OlivierBBB) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/opcode/OpCodeData.java:88]: Yes. But it makes more sense to have them defined on the instruction family level.

Comment (OlivierBBB) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/opcode/OpCodeData.java:88]: I moved these methods to the `OpCodeData` level.

**Review by letypequividelespoubelles — APPROVED** [review]
