### PR TITLE
fix: lookup txndata <-> wcp

### LINKED ISSUE #486: lokkup `txnData` -> `wcp` failing

### PR DESCRIPTION
**Pull request by letypequividelespoubelles**
Fixes #486

### CODE REVIEW

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/txn_data/TxnData.java [hunk 1]
```diff
@@ -45,6 +47,11 @@
 
 @RequiredArgsConstructor
 public class TxnData implements Module {
+  private final int nRowsFrontierTx = 7;
+  private final int nRowsAccessListTx = 8;
+  private final int nRowsEIP1559Tx = 8;
+  private final int nRowsTxMax =
```
Comment (delehef) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/txn_data/TxnData.java:53]: Make them `static` and full caps

**Review by delehef — CHANGES_REQUESTED** [review]

**Review by delehef — APPROVED** [review]
