### PR TITLE
Fix for initialization and finalization sections

### LINKED ISSUE #1648: Initialization and finalization sections fix
Fix based on https://github.com/Consensys/linea-specification/issues/11.

### PR DESCRIPTION
**Pull request by lorenzogentile404**
- spec: https://github.com/Consensys/linea-specification/issues/11
- constraints: https://github.com/Consensys/linea-constraints/pull/517.

### CODE REVIEW

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxInitializationSection.java [hunk 1]
```diff
@@ -127,20 +148,52 @@ public TxInitializationSection(Hub hub, WorldView world) {
...
+                recipientAfterValueTransfer, // Note that this depends on weather the sender is
+                // equal to the recipient
                 recipientAddress,
                 recipientDomSubStamps)
             .requiresRomlex(true));
+
     this.addFragments(
         ImcFragment.forTxInit(hub), ContextFragment.initializeExecutionContext(hub), txFragment);
 
+    boolean isRevertedTransaction = false; // TODO: how to get this?
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxInitializationSection.java]: You have to defer to post transaction to finish the initialization section.

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxInitializationSection.java [hunk 2]
```diff
@@ -37,7 +37,9 @@
 
 public class TxInitializationSection extends TraceSection {
 
-  @Getter private final AccountSnapshot senderAfterPayingForTransaction;
+  @Getter private final AccountSnapshot senderAfterPayingForGas;
+  @Getter private final AccountSnapshot senderAfterPayingForValue;
+  @Getter private final AccountSnapshot senderAfterPayingForGasAndValue;
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxInitializationSection.java]: I would suggest, for the sheer purpose of readability, to have the following snapshots be part of the class definition
```java
private final AccountSnapshot senderGasPayment
private final AccountSnapshot senderGasPaymentNew
private final AccountSnapshot senderValueTransfer
private final AccountSnapshot senderValueTransferNew
private final AccountSnapshot recipientValueReception
private final AccountSnapshot recipientValueReceptionNew
private AccountSnapshot senderUndoingValueTransfer
private AccountSnapshot senderUndoingValueTransferNew
private AccountSnapshot recipientUndoingValueReception
private AccountSnapshot recipientUndoingValueReceptionNew
```
I've started explicitly introducing all required `AccountSnapshot`'s as it became unmanageable otherwise in other sections (`CallSection` or `CreateSection` for instance.) As we handle a couple of hundred transactions total at a time max this isn't too much of an imposition on memory etc. And it makes intent more clear.

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxInitializationSection.java [hunk 3]
```diff
@@ -37,7 +37,9 @@
 
 public class TxInitializationSection extends TraceSection {
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxInitializationSection.java]: This has to `implements PostTransactionDefer` or whatever it's called.

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxFinalizationSection.java
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxFinalizationSection.java:1]: For this it would be ideal if we could get access to the refunded gas from Besu directly. I'm not sure we have it available here, or how, but we would need the values that are available here https://github.com/hyperledger/besu/blob/98780efd15ee3223de2c0cf2d144c8aaee30d5db/ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionProcessor.java#L502

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxInitializationSection.java (hunk 2 above)
Comment (lorenzogentile404) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxInitializationSection.java:42]: Ok.

Comment (lorenzogentile404) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxInitializationSection.java]: Do we actually need all of them? `senderGasPaymentNew` and `senderValueTransfer` should be the same. Also, I find clearer the notation "before" and "after". Anyway, let's discuss it tomorrow.

Comment (lorenzogentile404) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxInitializationSection.java]: Also, `senderValueTransferNew` and `senderUndoingValueTransfer`, `recipientValueReceptionNew` and `recipientUndoingValueReception` should be the same.

Comment (lorenzogentile404) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxInitializationSection.java]: Note: whenever variables represent the same thing, create a deep copy of the underlying objects.

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxInitializationSection.java [hunk 4]
```diff
@@ -38,73 +38,66 @@
...
 
     senderGasPayment =
         AccountSnapshot.fromAccount(
             senderAccount,
             tx.isSenderPreWarmed(),
             deploymentInfo.deploymentNumber(senderAddress),
             deploymentInfo.getDeploymentStatus(senderAddress));
-    senderDomSubStamps = DomSubStampsSubFragment.standardDomSubStamps(hub.stamp(), 0);
+    senderGasPaymentNew =
+        senderGasPayment.deepCopy().decrementBalanceBy(gasCost).turnOnWarmth().raiseNonceByOne();
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxInitializationSection.java:93]: Raising of the nonce.

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxInitializationSection.java [hunk 5]
```diff
@@ -38,73 +38,66 @@
...
-    final Wei valueAndGasCost = gasCost.add(value);
 
-    senderGasPaymentNew = senderGasPayment.deepCopy().decrementBalanceBy(gasCost).turnOnWarmth();
-    senderValueTransfer = senderGasPaymentNew.deepCopy();
+    final Wei value = (Wei) tx.getBesuTransaction().getValue();
 
-    senderValueTransferNew =
-        senderValueTransfer
-            .deepCopy()
-            .decrementBalanceBy(valueAndGasCost)
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxInitializationSection.java]: Gas was already paid for.

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxInitializationSection.java [hunk 6]
```diff
@@ -142,80 +129,82 @@ public TxInitializationSection(Hub hub, WorldView world) {
 
       recipientValueReceptionNew
           .raiseNonceByOne()
-          .incrementBalanceBy(incrementToApplyToRecipientBalance)
+          .incrementBalanceBy(value)
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxInitializationSection.java:148]: You always provide `value` to the recipient.

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxInitializationSection.java [hunk 7]
```diff
@@ -38,73 +38,66 @@
...
+  @Getter private final ContextFragment initializationContextFragment;
 
   public TxInitializationSection(Hub hub, WorldView world) {
-    super(hub, (short) 5);
-
-    // This ensures resolvePostTransaction is executed
+    super(hub, (short) 8);
     hub.defers().scheduleForPostTransaction(this);
 
+    hubStamp = hub.stamp();
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxInitializationSection.java:71]: Required for the `DOM`/`SUB` stamps in case of a `REVERT`ed transaction. The `HUB_STAMP` that you use is the one of the start of the transaction (in the `SUB_STAMP`.)

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxInitializationSection.java [hunk 8]
```diff
@@ -142,80 +129,82 @@ public TxInitializationSection(Hub hub, WorldView world) {
...
-        accountFragmentFactory.make(senderGasPayment, senderGasPaymentNew, senderDomSubStamps));
-
-    // ACC i+3 (sender)
-    this.addFragment(
+    this.addFragment( // ACC i + 3 (sender: value transfer)
         accountFragmentFactory.make(
-            senderValueTransfer, senderValueTransferNew, senderDomSubStamps));
+            senderValueTransfer,
+            senderValueTransferNew,
+            DomSubStampsSubFragment.standardDomSubStamps(hubStamp, 1)));
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxInitializationSection.java]: We need 2 different time stamps for the two actions (paying for gas / transferring value)

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxInitializationSection.java [hunk 9]
```diff
@@ -142,80 +129,82 @@ public TxInitializationSection(Hub hub, WorldView world) {
...
                 recipientValueReception,
                 recipientValueReceptionNew,
-                // Note that this depends on weather the sender is equal to the recipient
                 recipientAddress,
-                recipientDomSubStamps)
+                DomSubStampsSubFragment.standardDomSubStamps(hub.stamp(), 2))
             .requiresRomlex(true));
 
+    initializationContextFragment = ContextFragment.initializeExecutionContext(hub);
+
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxInitializationSection.java:181]: We create the ContextFragment that will be inserted at the very end of the transaction processing.

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxInitializationSection.java [hunk 10]
```diff
@@ -142,80 +129,82 @@ public TxInitializationSection(Hub hub, WorldView world) {
...
   @Override
   public void resolvePostTransaction(
       Hub hub, WorldView state, Transaction tx, boolean isSuccessful) {
+
     if (!isSuccessful) {
-      senderUndoingValueTransferNew =
-          senderUndoingValueTransfer.deepCopy().setDeploymentNumber(hub).incrementBalanceBy(value);
 
+      senderUndoingValueTransfer = senderValueTransferNew.deepCopy().setDeploymentNumber(hub);
+      senderUndoingValueTransferNew = senderValueTransfer.deepCopy().setDeploymentNumber(hub);
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxInitializationSection.java:198]: Doing things (_de_crementing by `value`) in reverse order amounts to doing the opposite (_in_crementing by `value`)

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxInitializationSection.java [hunk 11]
```diff
@@ -142,80 +129,82 @@ public TxInitializationSection(Hub hub, WorldView world) {
...
+              DomSubStampsSubFragment.revertWithCurrentDomSubStamps(hubStamp, revertStamp, 3)));
 
-      // ACC i+6 (recipient)
-      this.addFragment(
+      this.addFragment( // ACC i + 6 (recipient)
           accountFragmentFactory.make(
               recipientUndoingValueReception,
               recipientUndoingValueReceptionNew,
-              recipientDomSubStamps));
+              DomSubStampsSubFragment.revertWithCurrentDomSubStamps(hubStamp, revertStamp, 4)));
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxInitializationSection.java:217]: Here we use the `hub.stamp()` snapshot from transaction initialization.

**Comment by OlivierBBB** [comment]
For ignored tests of commit https://github.com/Consensys/linea-tracer/pull/1657/commits/76bbf00a76c44aa891843d2583a764a3ceee995c see https://github.com/Consensys/linea-tracer/issues/1578

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxFinalizationSection.java
Comment (lu-pinto) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/TxFinalizationSection.java:1]: The outermost frame should give you the refunds I believe, would need to double check it. It also gives you the selfDestructs and you can infer the maths as in the class you posted there.
I don't think you care about code delegation since you are on the London fork

**Review by OlivierBBB — APPROVED** [review]
