### PR TITLE
fix(modexpZero): mmio inst constant values

### LINKED ISSUE #1501: modexp_d20g0v0_London constraint breaking
In blochainRefTest 200

### PR DESCRIPTION
**Pull request by letypequividelespoubelles**

### CODE REVIEW

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmu/instructions/ModexpZero.java [hunk 1]
```diff
@@ -66,10 +67,10 @@ public MmuData setMicroInstructions(MmuData mmuData) {
         MmuToMmioConstantValues.builder()
             .exoSum(hubToMmuValues.exoSum())
             .phase(hubToMmuValues.phase())
-            .targetContextNumber(hubToMmuValues.targetId())
+            .exoId((int) hubToMmuValues.targetId())
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/mmu/instructions/ModexpZero.java:70]: the fix

File: linea-constraints
Comment (letypequividelespoubelles) [inline linea-constraints:1]: it was underconstraint (see https://github.com/Consensys/linea-specification-internal/pull/721)

**Review by OlivierBBB — APPROVED** [review]
LGTM
