### PR TITLE
fix & perf: add equal and hash annotation for rlpUtils calls

### LINKED ISSUE #2205: missing equalAndHash for RlpUtils

### PR DESCRIPTION
**Pull request by letypequividelespoubelles**

### CODE REVIEW

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/rlpUtils/InstructionByteStringPrefix.java [hunk 1]
```diff
@@ -30,19 +31,20 @@
...
-  @Getter private final boolean isList;
+  @EqualsAndHashCode.Include @Getter private final Bytes32 byteStringLength;
+  @EqualsAndHashCode.Include @Getter private final byte firstByte;
+  @EqualsAndHashCode.Include @Getter private final boolean isList;
 
   // outputs
   @Getter private boolean rlpPrefixRequired;
   private boolean byteStringIsNonEmpty;
-  @Getter private Bytes16 rlpPrefix;
+  @Getter private Bytes16 rlpPrefix = Bytes16.ZERO; // default value if no RLP prefix
```
Comment (amkCha) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/rlpUtils/InstructionByteStringPrefix.java]: Why do we need a default value now ?

**Comment by amkCha** [comment]
Very clear and clean ! Was a bit more complex of a fix :) Thanks for re-enabling the tests

**Review by amkCha — APPROVED** [review]

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/rlpUtils/InstructionByteStringPrefix.java (hunk 1 above)
Comment (letypequividelespoubelles) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/rlpUtils/InstructionByteStringPrefix.java]: because we don't, it was a tmp fix that is no longer required, thanks :)
