### PR TITLE
2079 multi except transient storage

### LINKED ISSUE #2079: EIP-1153 testing: multi exception tests for transient storage opcodes
Transient storage opcodes can produce
- `stackUnderflowException`
- `staticContextException` (for `TSTORE`)
- `outOfGasException`

We should test all possible combinations of them. We should make sure that the values that are touched, that is: both (transient) storage `key` and `value`, are **nonzero** when the failure happens, to avoid trivialities.

### PR DESCRIPTION
**Pull request by amkCha**
Closes #2079

### CODE REVIEW

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/imc/MxpCall.java [hunk 1]
```diff
@@ -131,21 +131,26 @@ public boolean getSize2NonZeroNoMxpx() {
...
+        ? getOpCodeData().billing().perUnit().cost()
+        : 0;
   }
 
   // Method only filled for LondonMxpCall
   protected void traceMayTriggerNonTrivialMmuOperationFromMxpx(Trace.Hub trace) {}
   ;
 
+  // Method only filled for LondonMxpCall
+  protected void traceMxpWords(Trace.Hub trace) {}
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/imc/MxpCall.java]: we have abstract method everywhere for fork dependant method, better keep the same pattern

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/transients/TStoreSection.java [hunk 2]
```diff
@@ -44,7 +44,7 @@ public TStoreSection(Hub hub) {
 
     if (Exceptions.any(exceptions)) {
       checkArgument(
-          Exceptions.stackException(exceptions) || Exceptions.outOfGasException(exceptions),
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/transients/TStoreSection.java:47]: oh wow !

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/mxp/moduleOperation/CancunMxpOperation.java [hunk 3]
```diff
@@ -52,7 +52,7 @@ protected int computeLineCount() {
 
   @Override
   public final void trace(int stamp, Trace.Mxp trace) {
-    traceDecoder(++stamp, trace);
+    traceDecoder(stamp, trace);
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/mxp/moduleOperation/CancunMxpOperation.java]: when is the stamp incremented ?

File: arithmetization/src/main/java/net/consensys/linea/zktracer/opcode/OpCode.java [hunk 4]
```diff
@@ -319,7 +320,10 @@ public boolean mayTriggerStaticException() {
     return this.getData().stackSettings().forbiddenInStatic();
   }
 
-  public boolean mayTriggerMemoryExpansionException() {
-    return this != MSIZE && this.getData().billing().type() != MxpType.NONE;
+  public boolean mayTriggerMemoryExpansionException(Fork fork) {
+    if (isPostCancun(fork)) {
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/opcode/OpCode.java]: more readable with a switch(fork) imho

File: arithmetization/src/main/java/net/consensys/linea/zktracer/runtime/stack/Stack.java [hunk 5]
```diff
@@ -134,7 +134,9 @@ private void threeOne(MessageFrame frame, StackContext pending) {
   }
 
   private void loadStore(MessageFrame frame, StackContext pending) {
-    if (currentOpcodeData.mnemonic().isAnyOf(OpCode.MSTORE, OpCode.MSTORE8, OpCode.SSTORE)) {
+    if (currentOpcodeData
+        .mnemonic()
+        .isAnyOf(OpCode.MSTORE, OpCode.MSTORE8, OpCode.SSTORE, OpCode.TSTORE)) {
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/runtime/stack/Stack.java:139]: nice catch

File: arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/OutOfGasExceptionTest.java [hunk 6]
```diff
@@ -286,4 +286,51 @@ void outOfGasExceptionJumpi(int cornerCase) {
     ExceptionUtils.assertEqualsOutOfGasIfCornerCaseMinusOneElseAssertNotEquals(
         cornerCase, bytecodeRunner);
   }
+
+  /** We provide a non-zero key and value to store in transient storage to avoid trivialities */
+  @Tag("cancun")
```
Comment (letypequividelespoubelles) [inline arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/OutOfGasExceptionTest.java]: why we don't run this test before cancun ? The bytecode is still possible to run, we would just get an invalid opcode. But the tracer must be able to run this tes for london and shanghai too, so I would remove the tag and run it for all forks

File: arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/OutOfGasExceptionTest.java [hunk 7]
```diff
@@ -286,4 +286,51 @@ void outOfGasExceptionJumpi(int cornerCase) {
...
+
+    long gasCost = bytecodeRunner.runOnlyForGasCost(testInfo);
+
+    bytecodeRunner.run(gasCost + cornerCase, testInfo);
+
+    ExceptionUtils.assertEqualsOutOfGasIfCornerCaseMinusOneElseAssertNotEquals(
+        cornerCase, bytecodeRunner);
+  }
+
+  @Tag("cancun")
```
Comment (letypequividelespoubelles) [inline arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/OutOfGasExceptionTest.java]: same

File: arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/OutOfGasMemExpExceptionTest.java [hunk 8]
```diff
@@ -479,4 +480,30 @@ void outOfGasExceptionLog4(int cornerCase) {
     ExceptionUtils.assertEqualsOutOfGasIfCornerCaseMinusOneElseAssertNotEquals(
         cornerCase, bytecodeRunner);
   }
+
+  @Tag("cancun")
```
Comment (letypequividelespoubelles) [inline arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/OutOfGasMemExpExceptionTest.java]: same

File: arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/multiExceptions/CallTest.java [hunk 9]
```diff
@@ -50,6 +51,7 @@ In this test, we trigger all subsets possible of exceptions (except stack except
 Note : As MXPX is a subcase of OOGX, we don't test MXPX & OOGX
  */
 
+@Tag("disabled-for-cancun-temporarily")
```
Comment (letypequividelespoubelles) [inline arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/multiExceptions/CallTest.java]: what's the purpose of this ?

File: arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/multiExceptions/CreatesTest.java [hunk 10]
```diff
@@ -52,14 +53,15 @@ In this test, we trigger all subsets possible of exceptions (except stack except
 Note : As MXPX is a subcase of OOGX, we don't test MXPX & OOGX
  */
 
+@Tag("disabled-for-cancun-temporarily")
```
Comment (letypequividelespoubelles) [inline arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/multiExceptions/CreatesTest.java]: ?

File: arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/multiExceptions/TstoreTest.java [hunk 11]
```diff
@@ -0,0 +1,69 @@
...
+/*
+In this test, we trigger all subsets possible of exceptions (except stack exceptions) at the same time for transients opcodes.
+List of the combinations tested below
+STATIC & OOGX : TSTORE, TLOAD
+ */
+@ExtendWith(UnitTestWatcher.class)
+public class TstoreTest extends TracerTestBase {
+
+  @Test
+  @Tag("cancun")
```
Comment (letypequividelespoubelles) [inline arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/multiExceptions/TstoreTest.java]: same

File: gradle/tests.gradle [hunk 12]
```diff
@@ -161,6 +161,12 @@ tasks.test.configure {
     excludeTags("replay")
     excludeTags("weekly")
     excludeTags("prc-calltests")
+    if (System.getenv("ZKEVM_FORK") != "CANCUN") {
```
Comment (letypequividelespoubelles) [inline gradle/tests.gradle]: I would remove this. All tests should be able to run for all forks imho, even if the behaviour is different depending on the fork. It'll test that cancun opcode are considered as invalid pre cancun

**Review by letypequividelespoubelles — APPROVED** [review]
LGTM with some comments, please address it before merging

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/mxp/moduleOperation/CancunMxpOperation.java (hunk 3 above)
Comment (amkCha) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/mxp/moduleOperation/CancunMxpOperation.java]: It's incremented here `arithmetization/src/main/java/net/consensys/linea/zktracer/module/mxp/module/Mxp.java` in the commit method 
```
    int stamp = 0;
    for (MxpOperation op : operations().getAll()) {
      op.trace(++stamp, trace.mxp());
    }
  }
```

File: arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/multiExceptions/CallTest.java (hunk 9 above)
Comment (amkCha) [reply arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/multiExceptions/CallTest.java]: So they are a lot of tests that are stuck on a while loop for Cancun. I'm disabling them in this PR and will reenable them in the following PR here https://github.com/Consensys/linea-tracer/pull/2145 it'll fix `MxpTestUtils` for Cancun (issue because we don't have types anymore for MXP opcodes)

File: arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/multiExceptions/CreatesTest.java (hunk 10 above)
Comment (amkCha) [reply arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/multiExceptions/CreatesTest.java]: same as above :)

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/transients/TStoreSection.java (hunk 2 above)
Comment (amkCha) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/transients/TStoreSection.java:47]: it does have 3 letters in common !

File: arithmetization/src/main/java/net/consensys/linea/zktracer/opcode/OpCode.java (hunk 4 above)
Comment (amkCha) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/opcode/OpCode.java]: ok, changed that !

File: gradle/tests.gradle (hunk 12 above)
Comment (amkCha) [reply gradle/tests.gradle]: Ok noted, making it run for all forks with different behaviors :ok_hand:

File: arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/multiExceptions/TstoreTest.java (hunk 11 above)
Comment (amkCha) [reply arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/multiExceptions/TstoreTest.java]: okay removed

File: arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/OutOfGasMemExpExceptionTest.java (hunk 8 above)
Comment (amkCha) [reply arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/OutOfGasMemExpExceptionTest.java]: removed

File: arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/OutOfGasExceptionTest.java (hunk 7 above)
Comment (amkCha) [reply arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/OutOfGasExceptionTest.java]: removed

File: arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/OutOfGasExceptionTest.java (hunk 6 above)
Comment (amkCha) [reply arithmetization/src/test/java/net/consensys/linea/zktracer/exceptions/OutOfGasExceptionTest.java]: ok got it, i'm making it run for all forks :+1:

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/imc/MxpCall.java (hunk 1 above)
Comment (amkCha) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/fragment/imc/MxpCall.java]: ok done :+1:

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/mxp/moduleOperation/CancunMxpOperation.java (hunk 3 above)
Comment (letypequividelespoubelles) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/mxp/moduleOperation/CancunMxpOperation.java]: yes, it's better as it will be common with the london one !

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/mxp/moduleCall/CancunMxpCall.java [hunk 13]
```diff
@@ -124,4 +130,65 @@ public void setMxpxFromMxpxExpression() {
...
+
+    this.mxpxExpression = mxpxExpression1 + mxpxExpression2;
+  }
+
+  public void traceMayTriggerNonTrivialMmuOperationFromMxpx(Trace.Hub trace) {
+    // From Cancun and on, we don't trace mayTriggerNonTrivialMmuOperationFromMxpx anymore
+  }
+
+  public void traceMxpWords(Trace.Hub trace) {
+    // TODO: check with Lorenzo to match mxp
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/mxp/moduleCall/CancunMxpCall.java]: ? is it ok ?

File: arithmetization/src/test/java/net/consensys/linea/zktracer/cancunTests/TransientTest.java [hunk 14]
```diff
@@ -102,6 +112,11 @@ public static Stream<Arguments> fourCalls() {
 
   @Test
   void trivialTStoreTLoad() {
```
Comment (letypequividelespoubelles) [inline arithmetization/src/test/java/net/consensys/linea/zktracer/cancunTests/TransientTest.java]: do we really need this test ? The first TLOAD of the sandwich tload tstore return 0, so I guess this new test doesn't bring anythig new. BUT: I see that the sandwich tload tstore is missing a `POP` after the TLOAD, could you fix this on this PR plz ? 

Thx

**Review by letypequividelespoubelles — APPROVED** [review]

File: arithmetization/src/test/java/net/consensys/linea/zktracer/cancunTests/TransientTest.java (hunk 14 above)
Comment (amkCha) [reply arithmetization/src/test/java/net/consensys/linea/zktracer/cancunTests/TransientTest.java]: Yes you're right, that's what it was missing, the POP and that's why we couldn't see the issue with TSTORE because there was still an item on the stack. I've removed the added test and fixed with the addition of a POP :ok_hand:

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/mxp/moduleCall/CancunMxpCall.java (hunk 13 above)
Comment (amkCha) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/mxp/moduleCall/CancunMxpCall.java]: I think I'll merge like this as the tests are passing and it corresponds to the spec. But I have it on my to do list to counter check with @lorenzogentile404 upon his return :+1:
