### PR TITLE
fix: selfdestruct recipient account row

### LINKED ISSUE #2120: fix: failing constraints in blockchain reference tests
We have the following [constraints failing](https://github.com/Consensys/linea-tracer/actions/runs/16010092771/job/45165776123) for the test `CREATE2_Suicide_d4g0v0_London`:

```
             failing constraint hub.account-consistency---linking---conflation-level---code#0:
                                |  30 |  31 |   32 |   33 |   34 |   35 |
                  acp_CODE_SIZE | 0x0 | 0x2 |  0x0 | *0x0 |  0x0 | 0x10 |
              acp_CODE_SIZE_NEW | 0x2 | 0x0 | *0x2 |  0x0 | 0x10 | 0x10 |
               acp_AGAIN_IN_CNF | 0x0 | 0x1 |  0x1 | *0x1 |  0x0 |  0x1 |
             
             failing constraint hub.account-consistency---linking---conflation-level---deployment-number-and-status#1:
                                        |  30 |  31 |   32 |   33 |  34 |  35 |
                  acp_DEPLOYMENT_STATUS | 0x0 | 0x1 |  0x0 | *0x0 | 0x0 | 0x1 |
              acp_DEPLOYMENT_STATUS_NEW | 0x1 | 0x0 | *0x1 |  0x0 | 0x1 | 0x1 |
                       acp_AGAIN_IN_CNF | 0x0 | 0x1 |  0x1 | *0x1 | 0x0 | 0x1 |
            
             failing constraint hub.selfdestruct-instruction---generalities-for-the-second-account-row#4:
                                                       |  24 |         25 |   26 |   27 |         28 |  29 |   30 |  31 |         32 |
                                      PEEK_AT_SCENARIO | 0x0 |        0x0 |  0x0 | *0x1 |        0x0 | 0x0 |  0x0 | 0x0 |        0x0 |
                                     account/CODE_SIZE | 0x0 | 0x5d2b47d5 |  0x0 |  0x0 | 0x5d2b47d5 | 0x2 | *0x0 | 0x0 | 0x6295ee1b |
                                 account/CODE_SIZE_NEW | 0x0 |        0x1 |  0x0 |  0x0 |        0x1 | 0x0 | *0x2 | 0x0 |        0x2 |
                                         stack/STATICX | 0x0 |        0x0 | *0x0 | *0x0 |        0x0 | 0x0 |  0x0 | 0x0 |        0x0 |
                     scenario/SELFDESTRUCT_WILL_REVERT | 0x0 |        0x0 |  0x1 | *0x0 |        0x0 | 0x0 |  0x0 | 0x0 |        0x0 |
              scenario/SELFDESTRUCT_WONT_REVERT_ALREAD | 0x0 |        0x0 |  0x0 | *0x0 |        0x0 | 0x0 |  0x0 | 0x0 |        0x0 |
              scenario/SELFDESTRUCT_WONT_REVERT_NOT_YE | 0x0 |        0x0 |  0x0 | *0x1 |        0x0 | 0x0 |  0x0 | 0x0 |        0x0 |
             
             failing constraint hub.selfdestruct-instruction---generalities-for-the-second-account-row#8:
                                                       |  24 |  25 |   26 |   27 |  28 |  29 |   30 |  31 |  32 |
                                      PEEK_AT_SCENARIO | 0x0 | 0x0 |  0x0 | *0x1 | 0x0 | 0x0 |  0x0 | 0x0 | 0x0 |
                             account/DEPLOYMENT_STATUS | 0x0 | 0x0 |  0x0 |  0x0 | 0x0 | 0x1 | *0x0 | 0x0 | 0x1 |
                         account/DEPLOYMENT_STATUS_NEW | 0x0 | 0x0 |  0x0 |  0x0 | 0x0 | 0x0 | *0x1 | 0x0 | 0x0 |
                                         stack/STATICX | 0x0 | 0x0 | *0x0 | *0x0 | 0x0 | 0x0 |  0x0 | 0x0 | 0x0 |
                     scenario/SELFDESTRUCT_WILL_REVERT | 0x0 | 0x0 |  0x1 | *0x0 | 0x0 | 0x0 |  0x0 | 0x0 | 0x0 |
              scenario/SELFDESTRUCT_WONT_REVERT_ALREAD | 0x0 | 0x0 |  0x0 | *0x0 | 0x0 | 0x0 |  0x0 | 0x0 | 0x0 |
              scenario/SELFDESTRUCT_WONT_REVERT_NOT_YE | 0x0 | 0x0 |  0x0 | *0x1 | 0x0 | 0x0 |  0x0 | 0x0 | 0x0 |
```

Other failing tests are:

* `CREATE_ContractSuicideDuringInit_WithValueToItself_d0g0v0_London`
* `TransactionCreateSuicideInInitcode_d0g0v0_London`

### PR DESCRIPTION
**Pull request by letypequividelespoubelles**

### CODE REVIEW

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/halt/SelfdestructSection.java [hunk 1]
```diff
@@ -183,7 +182,10 @@ public void resolvePostExecution(
     if (selfdestructTargetsItself()) {
       recipient = selfdestructorNew.deepCopy();
     }
-    recipientNew = AccountSnapshot.canonical(hub, recipientAddress);
+    recipientNew =
+        AccountSnapshot.canonical(hub, recipientAddress)
+            .setDeploymentStatus(recipient.deploymentStatus())
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/halt/SelfdestructSection.java:187]: this is the fix.

**Review by amkCha — APPROVED** [review]

**Comment by amkCha** [comment]
Well done finding for finding the fix ! Nice to add a test as well :+1:
