### PR TITLE
fix(mxp): used constants

### LINKED ISSUE #734: fix(mxp): used constants

### PR DESCRIPTION
**Pull request by lorenzogentile404**

### CODE REVIEW

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/mxp/MxpData.java [hunk 1]
```diff
@@ -380,11 +381,11 @@ private mxpExecutionPath getMxpExecutionPath() {
     return mxpExecutionPath.NON_TRIVIAL;
   }
 
-  public int maxCt() {
+  public int ctMax() {
```
Comment (letypequividelespoubelles) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/mxp/MxpData.java:384]: isn't it nb of rows instead ?

**Review by letypequividelespoubelles — APPROVED** [review]
