### PR TITLE
fix(oob): inst modexp pircing f of max

### LINKED ISSUE #1106: fix(oob): inst modexp pricing f of max

### PR DESCRIPTION
**Pull request by lorenzogentile404**

### CODE REVIEW

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/oob/OobOperation.java [hunk 1]
```diff
@@ -1074,16 +1074,14 @@ private void setModexpPricing(ModexpPricingOobCall prcModexpPricingOobCall) {
         callToISZERO(1, BigInteger.ZERO, prcModexpPricingOobCall.getExponentLog());
 
     // row i + 2
-    final BigInteger fOfMax =
+    final BigInteger squareRootFOfMax =
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/oob/OobOperation.java]: We shouldn't call it that, maybe `ceilingOfMaxDividedBy8` or so ... But certainly not `squareRoot`

**Review by OlivierBBB — CHANGES_REQUESTED** [review]

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/oob/OobOperation.java (hunk 1 above)
Comment (lorenzogentile404) [reply arithmetization/src/main/java/net/consensys/linea/zktracer/module/oob/OobOperation.java]: Let's wait for the tests to finish. If they pass, then I'll fix the name and we force the merge

**Review by OlivierBBB — APPROVED** [review]
