### PR TITLE
fix(ReturnSection): max code size

### LINKED ISSUE #1312: Some Precondition failure in `ReturnSection`
again ReferenceTest 121

### PR DESCRIPTION
**Pull request by letypequividelespoubelles**

### CODE REVIEW

File: arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/halt/ReturnSection.java [hunk 1]
```diff
@@ -130,7 +129,7 @@ public ReturnSection(Hub hub) {
     // maxCodeSizeException case
     final boolean triggerOobForMaxCodeSizeException = Exceptions.maxCodeSizeException(exceptions);
     if (triggerOobForMaxCodeSizeException) {
-      final OobCall oobCall = new XCallOobCall();
+      final OobCall oobCall = new DeploymentOobCall();
```
Comment (OlivierBBB) [inline arithmetization/src/main/java/net/consensys/linea/zktracer/module/hub/section/halt/ReturnSection.java:132]: Oh wow ^^

**Review by OlivierBBB — APPROVED** [review]
LGTM
